from __future__ import annotations

MESSAGES: dict[str, dict[str, str]] = {
    "init.twins_manage": {"it": "Gestisco gli archetipi", "en": "Manage the archetypes"},
    "init.errors.USER_TWIN_REVISION_PENDING": {
        "it": "Decidi prima la revisione dello User Twin in attesa.",
        "en": "Decide the pending User Twin revision first.",
    },
    "init.help": {
        "it": "Crea un progetto e lo porta dall'idea alla Definizione approvata",
        "en": "Create a project and take it from the idea to an approved Definition",
    },
    "init.option_name": {"it": "nome del progetto", "en": "name of the project"},
    "init.option_idea": {
        "it": "l'idea, in una o due frasi",
        "en": "the idea, in one or two sentences",
    },
    "init.option_mode": {
        "it": "design: solo design (predefinito); design-code: design e poi codice",
        "en": "design: design only (default); design-code: design and then code",
    },
    "init.option_project": {
        "it": "collega questa cartella a un progetto che esiste già nello Studio",
        "en": "link this folder to a project that already exists in the Studio",
    },
    "init.option_answers": {
        "it": "file JSON con le risposte, per fare tutto il percorso senza domande",
        "en": "JSON file with the answers, to run the whole path without questions",
    },
    "init.option_until": {
        "it": "si ferma dopo il passo indicato: brief (Brief), team (Prospettive), twins (User "
        "Twin) oppure requirements (Definizione)",
        "en": "stop after the named step: brief (Brief), team (Perspectives), twins (User Twin) "
        "or requirements (Definition)",
    },
    "init.welcome": {
        "it": "Nuovo progetto di OrchesTwin in questa cartella.",
        "en": "New OrchesTwin project in this folder.",
    },
    "init.path": {
        "it": "Il percorso ha quattro passi: Brief, Prospettive, User Twin e Definizione. Lo "
        "Studio prepara ogni passo con il suo modello e tu lo approvi qui; quello che approvi "
        "resta salvato anche se ti fermi a metà.",
        "en": "The path has four steps: Brief, Perspectives, User Twin and Definition. The "
        "Studio prepares each step with its model and you approve it here; what you approve "
        "stays saved even if you stop halfway.",
    },
    "init.mode_question": {"it": "Come vuoi lavorare?", "en": "How do you want to work?"},
    "init.mode_design_only": {
        "it": "Solo design (consigliato): arrivi a un design approvato",
        "en": "Design only (recommended): you get to an approved design",
    },
    "init.mode_design_and_code": {
        "it": "Design e codice: dopo il design, un comando successivo genera il codice",
        "en": "Design and code: after the design, a later command generates the code",
    },
    "init.mode_code_note": {
        "it": "Il codice lo genererà un comando successivo: anche in questa modalità il "
        "percorso parte dal design.",
        "en": "The code will be generated by a later command: in this mode too the path "
        "starts from the design.",
    },
    "init.mode_updated": {
        "it": "Modalità del progetto aggiornata: {mode}.",
        "en": "Mode of the project updated: {mode}.",
    },
    "init.idea": {
        "it": "Racconta la tua idea in una o due righe: che cosa vuoi realizzare, e per chi?",
        "en": "Tell your idea in one or two lines: what do you want to build, and for whom?",
    },
    "init.idea_required": {
        "it": "Serve almeno una riga con l'idea per partire.",
        "en": "At least one line with the idea is needed to start.",
    },
    "init.idea_too_long": {
        "it": "L'idea è troppo lunga: scrivila in al massimo {limit} caratteri.",
        "en": "The idea is too long: write it in at most {limit} characters.",
    },
    "init.name": {"it": "Nome del progetto:", "en": "Name of the project:"},
    "init.name_too_long": {
        "it": "Il nome deve avere al massimo {limit} caratteri.",
        "en": "The name must have at most {limit} characters.",
    },
    "init.created": {
        "it": "Progetto «{name}» creato nello Studio. Il collegamento con questa cartella è "
        "in {path}.",
        "en": 'Project "{name}" created in the Studio. The link with this folder is in {path}.',
    },
    "init.attaching": {
        "it": "Collego questa cartella al progetto «{name}» dello Studio.",
        "en": 'Linking this folder to the project "{name}" of the Studio.',
    },
    "init.linked": {
        "it": "Cartella collegata al progetto «{name}»: il collegamento è in {path}.",
        "en": 'Folder linked to the project "{name}": the link is in {path}.',
    },
    "init.resume": {
        "it": "Riprendo il progetto «{name}» dal passo {number} di {total}: {step}.",
        "en": 'Resuming the project "{name}" from step {number} of {total}: {step}.',
    },
    "init.resume_done": {
        "it": "Il progetto «{name}» ha già approvati i passi Brief, Prospettive, User Twin e "
        "Definizione.",
        "en": 'The project "{name}" already has the steps Brief, Perspectives, User Twin and '
        "Definition approved.",
    },
    "init.state_changed": {
        "it": "Il progetto è cambiato nel frattempo, forse dall'interfaccia web ({code}): "
        "rileggo lo stato e continuo da lì.",
        "en": "The project changed in the meantime, perhaps from the web interface ({code}): "
        "reading its state again and going on from there.",
    },
    "init.step_heading": {
        "it": "Passo {number} di {total}: {step}",
        "en": "Step {number} of {total}: {step}",
    },
    "init.already_approved": {
        "it": "Passo «{step}» già approvato (versione {version}).",
        "en": 'Step "{step}" already approved (version {version}).',
    },
    "init.step_approved": {
        "it": "Passo «{step}» approvato (versione {version}). Salvato in {path}.",
        "en": 'Step "{step}" approved (version {version}). Saved in {path}.',
    },
    "init.folder_updated": {
        "it": "Cartella di conoscenza aggiornata in orchestwin/ (versione {version}): contiene i "
        "passi approvati finora.",
        "en": "Knowledge folder updated in orchestwin/ (version {version}): it holds the steps "
        "approved so far.",
    },
    "init.folder_not_updated": {
        "it": "La cartella di conoscenza non è stata aggiornata ({code}): il percorso continua, e "
        "puoi scaricarla più tardi con `ut package publish`.",
        "en": "The knowledge folder was not updated ({code}): the path goes on, and you can "
        "download it later with `ut package publish`.",
    },
    "init.until_stop": {
        "it": "Mi fermo dopo il passo «{step}», come chiesto con --until. Rilancia `ut init` "
        "per continuare con il passo «{next}».",
        "en": 'Stopping after the step "{step}", as asked with --until. Launch `ut init` '
        'again to go on with the step "{next}".',
    },
    "init.done": {
        "it": "Fatto: il progetto «{name}» ha approvati tutti i passi fino alla Definizione.",
        "en": 'Done: the project "{name}" has every step approved up to the Definition.',
    },
    "init.done_step": {"it": "- {step}: versione {version}", "en": "- {step}: version {version}"},
    "init.done_saved": {
        "it": "Le versioni approvate sono in {steps}; il collegamento con lo Studio è in {link}.",
        "en": "The approved versions are in {steps}; the link with the Studio is in {link}.",
    },
    "init.next_design": {
        "it": "Il prossimo comando è `ut design`: prepara le alternative di design e ti fa "
        "scegliere quella da approvare.",
        "en": "The next command is `ut design`: it prepares the design alternatives and lets "
        "you choose the one to approve.",
    },
    "init.generation_resumed": {
        "it": "{label}: una generazione di questo passo è già in corso nello Studio, la seguo "
        "invece di avviarne un'altra.",
        "en": "{label}: a generation of this step is already running in the Studio; following "
        "it instead of starting another one.",
    },
    "init.busy": {
        "it": "Nello Studio girano già troppe generazioni: aspetto {seconds} secondi e "
        "riprovo (tentativo {attempt} di {attempts}).",
        "en": "Too many generations are already running in the Studio: waiting {seconds} "
        "seconds and trying again (attempt {attempt} of {attempts}).",
    },
    "init.generation_failed": {
        "it": "{label}: il modello non ha dato un risultato valido ({code}).",
        "en": "{label}: the model did not give a valid result ({code}).",
    },
    "init.retry_confirm": {
        "it": "Riprovo una volta? È una nuova generazione, circa {amount} USD.",
        "en": "Try once more? It is a new generation, about {amount} USD.",
    },
    "init.retry_assumed": {
        "it": "Riprovo una volta, perché con --yes hai già confermato la spesa (circa "
        "{amount} USD).",
        "en": "Trying once more, because with --yes you already confirmed the spending "
        "(about {amount} USD).",
    },
    "init.retry_confirm_subscription": {
        "it": "Riprovo una volta? È una nuova generazione, con l'abbonamento di Claude: non "
        "spende credito.",
        "en": "Try once more? It is a new generation, on the Claude subscription: it spends no "
        "credit.",
    },
    "init.retry_assumed_subscription": {
        "it": "Riprovo una volta, perché con --yes hai già dato il tuo consenso (è una nuova "
        "generazione con l'abbonamento di Claude: non spende credito).",
        "en": "Trying once more, because with --yes you already gave your consent (it is a new "
        "generation on the Claude subscription: it spends no credit).",
    },
    "init.dialogue_starting": {
        "it": "L'analista delle esigenze legge l'idea e prepara la prima domanda…",
        "en": "The needs analyst reads the idea and prepares the first question…",
    },
    "init.dialogue_label": {"it": "Dialogo del brief", "en": "Dialogue of the brief"},
    "init.dialogue_intro": {
        "it": "Ti faccio qualche domanda sull'idea, una alla volta. Quando rispondi:",
        "en": "I will ask a few questions about the idea, one at a time. When you answer:",
    },
    "init.dialogue_rule_unknown": {
        "it": "- una risposta vuota oppure ? vuol dire «non lo so, proponilo tu»;",
        "en": '- an empty answer or ? means "I do not know, propose it yourself";',
    },
    "init.dialogue_rule_done": {
        "it": "- /fine compone il brief con quello che hai detto finora (va bene anche /done);",
        "en": "- /done composes the brief with what you said so far (/fine works too);",
    },
    "init.dialogue_rule_quit": {
        "it": "- /esci chiude ut init: rilanciandolo riprendi da questa domanda (va bene anche "
        "/quit).",
        "en": "- /quit closes ut init: launching it again resumes from this question (/esci "
        "works too).",
    },
    "init.dialogue_open": {
        "it": "Punti essenziali ancora aperti: {count}.",
        "en": "Essential points still open: {count}.",
    },
    "init.dialogue_question": {
        "it": "Domanda {number}: {question}",
        "en": "Question {number}: {question}",
    },
    "init.dialogue_list_hint": {
        "it": "Scrivi un elemento per riga; una riga vuota conclude.",
        "en": "Write one item per line; an empty line ends the list.",
    },
    "init.dialogue_answer": {"it": "Risposta:", "en": "Answer:"},
    "init.answer_too_many": {
        "it": "Sono troppi elementi: al massimo {limit}. Riprova.",
        "en": "Too many items: at most {limit}. Try again.",
    },
    "init.answer_too_long": {
        "it": "La risposta è troppo lunga: al massimo {limit} caratteri. Riprova.",
        "en": "The answer is too long: at most {limit} characters. Try again.",
    },
    "init.dialogue_essentials_done": {
        "it": "Il brief ha già tutti i punti essenziali.",
        "en": "The brief already has every essential point.",
    },
    "init.dialogue_more": {
        "it": "Vuoi rispondere ad altre domande per renderlo più preciso, o comporlo adesso?",
        "en": "Do you want to answer more questions to make it more precise, or compose it now?",
    },
    "init.dialogue_more_yes": {
        "it": "Rispondo ad altre domande (con /fine lo componi quando vuoi)",
        "en": "Answer more questions (/done composes it whenever you want)",
    },
    "init.dialogue_more_no": {"it": "Componi il brief adesso", "en": "Compose the brief now"},
    "init.dialogue_scripted": {
        "it": "Risposta dal file: {answer}",
        "en": "Answer from the file: {answer}",
    },
    "init.dialogue_scripted_unknown": {
        "it": "Risposta dal file: non lo so, lo propone il modello.",
        "en": "Answer from the file: I do not know, the model proposes it.",
    },
    "init.dialogue_ready": {
        "it": "Le domande sono finite: compongo il brief.",
        "en": "The questions are over: composing the brief.",
    },
    "init.dialogue_left": {
        "it": "Ti fermi qui: il dialogo resta aperto nello Studio. Rilancia `ut init` per "
        "riprendere da questa domanda.",
        "en": "You stop here: the dialogue stays open in the Studio. Launch `ut init` again to "
        "resume from this question.",
    },
    "init.compose_label": {"it": "Compongo il brief", "en": "Composing the brief"},
    "init.compose_unchanged": {
        "it": "Il brief composto è uguale alla versione che c'è già: tengo quella.",
        "en": "The composed brief is the same as the version already there: keeping that one.",
    },
    "init.dialogue_unavailable": {
        "it": "Lo Studio non ha un modello per il dialogo del brief "
        "(BRIEF_DIALOGUE_MODEL_NOT_CONFIGURED): ti chiedo io i punti essenziali. Quello che "
        "lasci vuoto resta un punto aperto.",
        "en": "The Studio has no model for the dialogue of the brief "
        "(BRIEF_DIALOGUE_MODEL_NOT_CONFIGURED): I ask you the essential points myself. What "
        "you leave empty stays an open point.",
    },
    "init.question_problem": {
        "it": "Quale problema risolve il progetto?",
        "en": "Which problem does the project solve?",
    },
    "init.question_target_users": {
        "it": "Chi userà il prodotto?",
        "en": "Who will use the product?",
    },
    "init.question_goals": {
        "it": "Quali risultati vuoi ottenere?",
        "en": "Which results do you want to reach?",
    },
    "init.question_functional_requirements": {
        "it": "Che cosa deve permettere di fare il prodotto?",
        "en": "What must the product let people do?",
    },
    "init.manual_left": {
        "it": "Ti fermi qui: del brief non ho salvato nulla. Rilancia `ut init` per "
        "ricominciare da queste domande.",
        "en": "You stop here: nothing of the brief was saved. Launch `ut init` again to start "
        "again from these questions.",
    },
    "init.manual_saved": {
        "it": "Brief salvato nello Studio (versione {version}).",
        "en": "Brief saved in the Studio (version {version}).",
    },
    "init.brief_heading": {
        "it": "Il brief (versione {version}):",
        "en": "The brief (version {version}):",
    },
    "init.brief_open": {
        "it": "Punti aperti, ancora da decidere: {fields}.",
        "en": "Open points, still to decide: {fields}.",
    },
    "init.proposals_intro": {
        "it": "Proposte del modello per i punti che non hai deciso: {count}.",
        "en": "Proposals of the model for the points you did not decide: {count}.",
    },
    "init.proposals_choice": {
        "it": "Che cosa fai con queste proposte?",
        "en": "What do you do with these proposals?",
    },
    "init.proposals_all": {"it": "Le accetto tutte", "en": "Accept them all"},
    "init.proposals_each": {"it": "Decido una per una", "en": "Decide one by one"},
    "init.proposals_none": {
        "it": "Non ne accetto nessuna: restano punti aperti",
        "en": "Accept none: they stay open points",
    },
    "init.proposal_accept": {
        "it": "Accetti la proposta {number} ({field})?",
        "en": "Do you accept proposal {number} ({field})?",
    },
    "init.proposal_reason": {
        "it": "Non accettata dal proprietario del progetto con ut init.",
        "en": "Not accepted by the owner of the project with ut init.",
    },
    "init.proposal_skipped": {
        "it": "La proposta {number} non si può più decidere: quel punto è già definito.",
        "en": "Proposal {number} can no longer be decided: that point is already defined.",
    },
    "init.proposals_done": {
        "it": "Proposte accettate: {accepted}; scartate: {rejected}. Il brief è alla "
        "versione {version}.",
        "en": "Proposals accepted: {accepted}; discarded: {rejected}. The brief is at "
        "version {version}.",
    },
    "init.brief_choice": {
        "it": "Che cosa fai con il brief?",
        "en": "What do you do with the brief?",
    },
    "init.brief_approve": {"it": "Lo approvo e vado avanti", "en": "Approve it and go on"},
    "init.brief_correct": {"it": "Correggo un punto", "en": "Correct a point"},
    "init.brief_stop": {"it": "Mi fermo qui", "en": "Stop here"},
    "init.brief_left": {
        "it": "Il brief resta in attesa della tua approvazione. Rilancia `ut init` per "
        "riprendere da qui.",
        "en": "The brief stays waiting for your approval. Launch `ut init` again to resume "
        "from here.",
    },
    "init.brief_incomplete": {
        "it": "Per approvare il brief mancano ancora questi punti: {fields}. Correggili, "
        "oppure scrivi ? per lasciarli aperti.",
        "en": "To approve the brief these points are still missing: {fields}. Correct them, "
        "or write ? to leave them open.",
    },
    "init.correct_which": {
        "it": "Quale punto vuoi correggere?",
        "en": "Which point do you want to correct?",
    },
    "init.correct_text": {
        "it": "Nuovo valore per «{field}» (? per lasciarlo aperto, riga vuota per annullare):",
        "en": 'New value for "{field}" (? to leave it open, empty line to cancel):',
    },
    "init.correct_list": {
        "it": "Nuovi elementi per «{field}», uno per riga; una riga vuota conclude. Scrivi ? "
        "per lasciarlo aperto, oppure subito una riga vuota per annullare.",
        "en": 'New items for "{field}", one per line; an empty line ends the list. Write ? to '
        "leave it open, or an empty line at once to cancel.",
    },
    "init.correct_cancelled": {
        "it": "Nessuna correzione: il brief resta com'era.",
        "en": "No correction: the brief stays as it was.",
    },
    "init.correct_saved": {
        "it": "Correzione salvata: il brief è alla versione {version}.",
        "en": "Correction saved: the brief is at version {version}.",
    },
    "init.correct_same": {
        "it": "Il valore è quello di prima: il brief non cambia.",
        "en": "The value is the same as before: the brief does not change.",
    },
    "init.field_name": {"it": "Nome", "en": "Name"},
    "init.field_description": {"it": "L'idea", "en": "The idea"},
    "init.field_problem": {"it": "Il problema", "en": "The problem"},
    "init.field_goals": {"it": "Obiettivi", "en": "Goals"},
    "init.field_target_users": {"it": "Per chi", "en": "For whom"},
    "init.field_domain": {"it": "Contesto", "en": "Context"},
    "init.field_technical_constraints": {"it": "Vincoli tecnici", "en": "Technical constraints"},
    "init.field_temporal_constraints": {"it": "Tempi", "en": "Timing"},
    "init.field_budget": {"it": "Budget", "en": "Budget"},
    "init.field_functional_requirements": {"it": "Cosa deve fare", "en": "What it must do"},
    "init.field_non_functional_requirements": {
        "it": "Qualità attese",
        "en": "Expected qualities",
    },
    "init.field_risks": {"it": "Rischi", "en": "Risks"},
    "init.field_stakeholders": {"it": "Persone coinvolte", "en": "People involved"},
    "init.field_available_artifacts": {
        "it": "Materiali disponibili",
        "en": "Available materials",
    },
    "init.field_definition_of_done": {"it": "Quando sarà finito", "en": "When it is done"},
    "init.designer_missing_end": {
        "it": "Attenzione: nelle prospettive approvate di questo progetto l'Esperienza d'uso "
        "(UX) non è applicata per intero, quindi le alternative di design non si possono "
        "preparare. Prepara di nuovo le prospettive e approvale nello Studio web.",
        "en": "Note: in the approved perspectives of this project User experience (UX) is not "
        "fully applied, so the design alternatives cannot be prepared. Prepare the "
        "perspectives again and approve them in the web Studio.",
    },
    "init.team_label": {"it": "Preparo le prospettive", "en": "Preparing the perspectives"},
    "init.team_heading": {
        "it": "Prospettive (versione {version})",
        "en": "Perspectives (version {version})",
    },
    "init.team_intro": {
        "it": "Le competenze con cui guardare il progetto: ognuna porta le sue considerazioni "
        "quando si scrivono requisiti e design.",
        "en": "The competences through which the project is looked at: each one adds its "
        "considerations when the requirements and the design are written.",
    },
    "init.team_outdated": {
        "it": "Questo Studio non dà ancora le prospettive: aggiornalo per vederle e cambiarle. "
        "Puoi comunque approvare questo passo.",
        "en": "This Studio does not give the perspectives yet: update it to see and change "
        "them. You can still approve this step.",
    },
    "init.team_choice": {
        "it": "Che cosa fai con le prospettive?",
        "en": "What do you do with the perspectives?",
    },
    "init.team_approve": {"it": "Le approvo e vado avanti", "en": "Approve them and go on"},
    "init.team_change": {"it": "Cambio le prospettive", "en": "Change the perspectives"},
    "init.team_stop": {"it": "Mi fermo qui", "en": "Stop here"},
    "init.team_left": {
        "it": "Le prospettive restano in attesa della tua approvazione. Rilancia `ut init` per "
        "riprendere da qui.",
        "en": "The perspectives stay waiting for your approval. Launch `ut init` again to "
        "resume from here.",
    },
    "init.team_nothing": {
        "it": "In questo progetto nessuna prospettiva e nessun aspetto si può attivare o togliere.",
        "en": "In this project no perspective and no aspect can be switched on or off.",
    },
    "init.team_switch_intro": {
        "it": "Prospettive e aspetti che puoi attivare [ ] o togliere [x]:",
        "en": "Perspectives and aspects you can switch on [ ] or off [x]:",
    },
    "init.team_switch": {
        "it": "Numeri da cambiare, separati da spazi (riga vuota per non cambiare nulla):",
        "en": "Numbers to switch, separated by spaces (empty line to change nothing):",
    },
    "init.team_switch_invalid": {
        "it": "Scrivi solo numeri da 1 a {count}, separati da spazi.",
        "en": "Write only numbers from 1 to {count}, separated by spaces.",
    },
    "init.team_unchanged": {
        "it": "Le prospettive non cambiano.",
        "en": "The perspectives do not change.",
    },
    "init.team_updated": {
        "it": "Prospettive aggiornate (versione {version}).",
        "en": "Perspectives updated (version {version}).",
    },
    "init.team_issue": {
        "it": "{name}: il cambio non è accettato ({code}).",
        "en": "{name}: the change is not accepted ({code}).",
    },
    "init.team_issue_duplicate_agent": {
        "it": "{name} compare due volte nella scelta.",
        "en": "{name} appears twice in the selection.",
    },
    "init.team_issue_duplicate_rationale": {
        "it": "Per {name} ci sono due motivazioni: ne basta una.",
        "en": "{name} has two reasons: one is enough.",
    },
    "init.team_issue_mandatory_agent_missing": {
        "it": "{name}: non si può togliere in questo progetto.",
        "en": "{name}: it cannot be switched off in this project.",
    },
    "init.team_issue_agent_not_selectable": {
        "it": "{name}: non si può attivare, perché il brief la esclude.",
        "en": "{name}: it cannot be switched on, because the brief rules it out.",
    },
    "init.team_issue_rationale_required": {
        "it": "{name}: per attivarla questo Studio chiede una motivazione, quindi attivala "
        "nello Studio web.",
        "en": "{name}: this Studio asks for a reason to switch it on, so switch it on in the "
        "web Studio.",
    },
    "init.team_issue_unused_rationale": {
        "it": "La motivazione per {name} non serve: non è un'aggiunta.",
        "en": "The reason for {name} is not needed: it is not an addition.",
    },
    "init.team_blocked": {
        "it": "{name}: il brief la esclude ({excluded}) e insieme la chiede ({required}).",
        "en": "{name}: the brief rules it out ({excluded}) and also asks for it ({required}).",
    },
    "init.team_asks": {"it": "la chiede con {words}", "en": "asks for it with {words}"},
    "init.team_rules_out": {"it": "la esclude con {words}", "en": "rules it out with {words}"},
    "init.team_evidence": {"it": "{terms} in {fields}", "en": "{terms} in {fields}"},
    "init.team_term": {"it": "«{term}»", "en": '"{term}"'},
    "init.standing_always": {"it": "Sempre applicata", "en": "Always applied"},
    "init.standing_required": {"it": "La chiede il brief", "en": "The brief asks for it"},
    "init.standing_optional": {"it": "A scelta", "en": "Your choice"},
    "init.standing_optional_applied": {
        "it": "Applicata, a tua scelta",
        "en": "Applied, your choice",
    },
    "init.standing_always_missing": {
        "it": "Questa versione è stata preparata prima che questa prospettiva diventasse sempre "
        "applicata: prepara di nuovo le prospettive nello Studio web.",
        "en": "This version was prepared before this perspective became always applied: prepare "
        "the perspectives again in the web Studio.",
    },
    "init.standing_excluded": {"it": "Il brief la esclude", "en": "The brief rules it out"},
    "init.standing_contested": {
        "it": "Il brief dice due cose diverse: decidi tu",
        "en": "The brief says two different things: you decide",
    },
    "init.perspective_ux": {"it": "Esperienza d'uso (UX)", "en": "User experience (UX)"},
    "init.perspective_ux_line": {
        "it": "Guarda il progetto con gli occhi di chi lo userà: obiettivi, contesto, punti in "
        "cui ci si può bloccare.",
        "en": "Looks at the project through the eyes of the people who will use it: goals, "
        "context, places where they may get stuck.",
    },
    "init.perspective_accessibility": {"it": "Accessibilità", "en": "Accessibility"},
    "init.perspective_accessibility_line": {
        "it": "Controlla che tutti possano usarlo: tastiera, contrasto, testi leggibili, "
        "messaggi chiari.",
        "en": "Checks that everyone can use it: keyboard, contrast, readable text, clear messages.",
    },
    "init.perspective_software_engineering": {
        "it": "Ingegneria del software",
        "en": "Software engineering",
    },
    "init.perspective_software_engineering_line": {
        "it": "Tiene il progetto realizzabile entro vincoli tecnici, tempi e budget, e "
        "verificabile.",
        "en": "Keeps the project feasible within its technical constraints, time and budget, "
        "and verifiable.",
    },
    "init.perspective_product": {"it": "Prodotto", "en": "Product"},
    "init.perspective_product_line": {
        "it": "Tiene le priorità: che cosa serve nella prima versione e che cosa può aspettare.",
        "en": "Keeps the priorities: what the first version needs and what can wait.",
    },
    "init.perspective_security": {"it": "Sicurezza", "en": "Security"},
    "init.perspective_security_line": {
        "it": "Protegge dati e accessi: chi può vedere e fare che cosa.",
        "en": "Protects data and access: who may see and do what.",
    },
    "init.aspect_web": {"it": "Interfaccia web", "en": "Web interface"},
    "init.aspect_web_line": {
        "it": "Funziona nel browser, dal telefono al computer.",
        "en": "Works in the browser, from phone to desktop.",
    },
    "init.aspect_services": {"it": "Servizi e dati", "en": "Services and data"},
    "init.aspect_services_line": {
        "it": "Dati e funzioni che stanno su un server.",
        "en": "Data and logic that live on a server.",
    },
    "init.aspect_mobile": {"it": "Mobile", "en": "Mobile"},
    "init.aspect_mobile_line": {
        "it": "Uso su telefono e tablet.",
        "en": "Use on phones and tablets.",
    },
    "init.aspect_integrations": {
        "it": "Collegamenti con altri sistemi",
        "en": "Connections to other systems",
    },
    "init.aspect_integrations_line": {
        "it": "Scambio di dati con servizi esterni.",
        "en": "Data exchanged with outside services.",
    },
    "init.profiles_label": {
        "it": "Propongo gli archetipi",
        "en": "Proposing the archetypes",
    },
    "init.profiles_intro": {
        "it": "Archetipi proposti dal modello: {count}. Per ciascuno scegli se "
        "confermarlo o scartarlo: dagli archetipi confermati nascono gli User Twin.",
        "en": "Archetypes proposed by the model: {count}. For each one, choose "
        "whether to confirm or discard it: the User Twins are made from the confirmed archetypes.",
    },
    "init.profile_heading": {
        "it": "Archetipo {number} di {total}: {name}",
        "en": "Archetype {number} of {total}: {name}",
    },
    "init.profile_confirmed": {
        "it": "Archetipo {number} di {total}, {name}: già confermato.",
        "en": "Archetype {number} of {total}, {name}: already confirmed.",
    },
    "init.profile_rejected": {
        "it": "Archetipo {number} di {total}, {name}: già scartato.",
        "en": "Archetype {number} of {total}, {name}: already discarded.",
    },
    "init.profile_confirm": {
        "it": "Confermi questo archetipo?",
        "en": "Do you confirm this archetype?",
    },
    "init.profile_needed": {
        "it": "Serve almeno un archetipo confermato per creare gli User Twin: questo è "
        "l'ultimo, quindi va confermato.",
        "en": "At least one confirmed archetype is needed to create the User Twins: this is the "
        "last one, so it has to be confirmed.",
    },
    "init.profile_reason": {
        "it": "Perché lo scarti? Una riga, resta scritta con l'archetipo:",
        "en": "Why do you discard it? One line, it stays written with the archetype:",
    },
    "init.profile_reason_default": {
        "it": "Non rappresenta gli utenti del progetto.",
        "en": "It does not represent the users of the project.",
    },
    "init.twins_label": {
        "it": "Creo gli User Twin dagli archetipi confermati",
        "en": "Creating the User Twins from the confirmed archetypes",
    },
    "init.twins_heading": {
        "it": "Gli User Twin (versione {version}). User Twin creati: {count}.",
        "en": "The User Twins (version {version}). User Twins created: {count}.",
    },
    "init.twin_heading": {
        "it": "User Twin {number} di {total}: {name}",
        "en": "User Twin {number} of {total}: {name}",
    },
    "init.detail_role": {"it": "Ruolo", "en": "Role"},
    "init.detail_summary": {"it": "In breve", "en": "In short"},
    "init.detail_goals": {"it": "Obiettivi", "en": "Goals"},
    "init.detail_difficulties": {"it": "Difficoltà", "en": "Difficulties"},
    "init.detail_context": {
        "it": "Dove e come usa il prodotto",
        "en": "Where and how they use the product",
    },
    "init.twins_choice": {
        "it": "Che cosa fai con gli User Twin?",
        "en": "What do you do with the User Twins?",
    },
    "init.twins_approve": {"it": "Li approvo e vado avanti", "en": "Approve them and go on"},
    "init.twins_stop": {"it": "Mi fermo qui", "en": "Stop here"},
    "init.twins_left": {
        "it": "Gli User Twin restano in attesa della tua approvazione. Rilancia `ut init` per "
        "riprendere da qui.",
        "en": "The User Twins stay waiting for your approval. Launch `ut init` again to resume "
        "from here.",
    },
    "init.requirements_wait": {
        "it": "Adesso lo Studio scrive i requisiti a partire dal brief e dagli User Twin: ci "
        "vogliono circa due minuti.",
        "en": "Now the Studio writes the requirements from the brief and the User Twins: it "
        "takes about two minutes.",
    },
    "init.requirements_label": {"it": "Scrivo i requisiti", "en": "Writing the requirements"},
    "init.requirements_heading": {
        "it": "I requisiti (versione {version}). Requisiti: {requirements}; storie degli utenti: "
        "{stories}; criteri di accettazione: {criteria}.",
        "en": "The requirements (version {version}). Requirements: {requirements}; user stories: "
        "{stories}; acceptance criteria: {criteria}.",
    },
    "init.column_code": {"it": "Codice", "en": "Code"},
    "init.column_title": {"it": "Titolo", "en": "Title"},
    "init.column_priority": {"it": "Priorità", "en": "Priority"},
    "init.priority_must": {"it": "indispensabile", "en": "must have"},
    "init.priority_should": {"it": "importante", "en": "should have"},
    "init.priority_could": {"it": "utile", "en": "could have"},
    "init.priority_wont_for_now": {"it": "non per ora", "en": "not for now"},
    "init.kind_functional": {"it": "funzione", "en": "function"},
    "init.kind_non_functional": {"it": "qualità", "en": "quality"},
    "init.kind_constraint": {"it": "vincolo", "en": "constraint"},
    "init.requirements_choice": {
        "it": "Che cosa fai con i requisiti?",
        "en": "What do you do with the requirements?",
    },
    "init.requirements_approve": {"it": "Li approvo e vado avanti", "en": "Approve them and go on"},
    "init.requirements_read": {
        "it": "Li leggo tutti: requisiti, storie e criteri di accettazione",
        "en": "Read them all: requirements, stories and acceptance criteria",
    },
    "init.requirements_change": {
        "it": "Chiedo una modifica a parole",
        "en": "Ask for a change in words",
    },
    "init.requirements_stop": {"it": "Mi fermo qui", "en": "Stop here"},
    "init.requirements_left": {
        "it": "I requisiti restano in attesa della tua approvazione. Rilancia `ut init` per "
        "riprendere da qui.",
        "en": "The requirements stay waiting for your approval. Launch `ut init` again to "
        "resume from here.",
    },
    "init.all_requirements": {"it": "Requisiti", "en": "Requirements"},
    "init.all_stories": {"it": "Storie degli utenti", "en": "User stories"},
    "init.all_criteria": {"it": "Criteri di accettazione", "en": "Acceptance criteria"},
    "init.requirement_line": {
        "it": "{code} {title} ({priority}, {kind})",
        "en": "{code} {title} ({priority}, {kind})",
    },
    "init.story_line": {
        "it": "{code} {twin} vuole {goal}, per {benefit}.",
        "en": "{code} {twin} wants to {goal}, so as to {benefit}.",
    },
    "init.story_someone": {"it": "Un utente", "en": "A user"},
    "init.criterion_check": {"it": "si verifica con {method}", "en": "checked by {method}"},
    "init.verify_automated_test": {"it": "un test automatico", "en": "an automated test"},
    "init.verify_manual_review": {"it": "una revisione a mano", "en": "a manual review"},
    "init.verify_inspection": {"it": "un'ispezione", "en": "an inspection"},
    "init.verify_demonstration": {"it": "una dimostrazione", "en": "a demonstration"},
    "init.verify_analysis": {"it": "un'analisi", "en": "an analysis"},
    "init.change_request": {
        "it": "Scrivi con parole tue che cosa vuoi cambiare nei requisiti (per annullare, "
        "subito una riga vuota).",
        "en": "Write in your own words what you want to change in the requirements (to "
        "cancel, an empty line at once).",
    },
    "init.change_cancelled": {"it": "Nessuna modifica chiesta.", "en": "No change requested."},
    "init.change_scripted": {
        "it": "Modifica chiesta dal file: {request}",
        "en": "Change requested by the file: {request}",
    },
    "init.change_label": {
        "it": "Preparo la modifica dei requisiti",
        "en": "Preparing the change to the requirements",
    },
    "init.change_unchanged": {
        "it": "Lo Studio non ha trovato niente da cambiare con questa richiesta: i requisiti "
        "restano come sono.",
        "en": "The Studio found nothing to change with this request: the requirements stay "
        "as they are.",
    },
    "init.change_waiting": {
        "it": "C'è una modifica dei requisiti proposta e non ancora decisa: eccola.",
        "en": "There is a proposed change to the requirements that is not decided yet: here it is.",
    },
    "init.change_heading": {
        "it": "La modifica proposta. Cambiamenti: {count}.",
        "en": "The proposed change. Changes: {count}.",
    },
    "init.change_add": {
        "it": "+ si aggiunge {what} {code}: {text}",
        "en": "+ adds {what} {code}: {text}",
    },
    "init.change_replace": {
        "it": "~ cambia {what} {code}: {text}",
        "en": "~ changes {what} {code}: {text}",
    },
    "init.change_remove": {
        "it": "- si toglie {what} {code}: {text}",
        "en": "- removes {what} {code}: {text}",
    },
    "init.change_other": {"it": "* {what} {code}: {text}", "en": "* {what} {code}: {text}"},
    "init.artifact_requirement": {"it": "il requisito", "en": "the requirement"},
    "init.artifact_user_story": {"it": "la storia", "en": "the story"},
    "init.artifact_acceptance_criterion": {"it": "il criterio", "en": "the criterion"},
    "init.artifact_scenario": {"it": "lo scenario", "en": "the scenario"},
    "init.artifact_need": {"it": "il bisogno", "en": "the need"},
    "init.artifact_journey": {"it": "il journey", "en": "the journey"},
    "init.artifact_risk": {"it": "il rischio", "en": "the risk"},
    "init.artifact_definition_of_done": {
        "it": "la condizione di fine lavoro",
        "en": "the done condition",
    },
    "init.change_apply": {"it": "Applichi questa modifica?", "en": "Do you apply this change?"},
    "init.change_reason": {
        "it": "Scartata dal proprietario del progetto con ut init.",
        "en": "Discarded by the owner of the project with ut init.",
    },
    "init.change_applied": {
        "it": "Modifica applicata: i requisiti sono alla versione {version}.",
        "en": "Change applied: the requirements are at version {version}.",
    },
    "init.change_discarded": {
        "it": "Modifica scartata: i requisiti restano alla versione {version}.",
        "en": "Change discarded: the requirements stay at version {version}.",
    },
    "init.errors.NOT_SIGNED_IN": {
        "it": "Per creare o continuare un progetto serve l'accesso allo Studio {studio}: "
        "accedi con `ut login`, poi rilancia `ut init`.",
        "en": "Creating or continuing a project needs a sign-in to the Studio {studio}: sign "
        "in with `ut login`, then launch `ut init` again.",
    },
    "init.errors.STUDIO_UNREACHABLE": {
        "it": "Lo Studio all'indirizzo {address} non risponde. Non si è perso niente: quello "
        "che hai approvato è salvato. Quando lo Studio torna raggiungibile, rilancia "
        "`ut init` e riprendi da dove eri.",
        "en": "The Studio at {address} does not answer. Nothing is lost: what you approved is "
        "saved. When the Studio can be reached again, launch `ut init` again and resume from "
        "where you were.",
    },
    "init.errors.INPUT_CLOSED": {
        "it": "L'input si è chiuso mentre aspettavo una risposta: non ho fatto altro. Non si è "
        "perso niente: quello che hai approvato è salvato, e rilanciando `ut init` riprendi dal "
        "primo passo non ancora approvato.",
        "en": "The input closed while an answer was awaited: nothing else was done. Nothing is "
        "lost: what you approved is saved, and launching `ut init` again continues from the "
        "first step that is not approved yet.",
    },
    "init.errors.SPENDING_REFUSED": {
        "it": "Non è partita nessuna generazione, perché la spesa non è stata confermata. "
        "Rilancia `ut init` quando vuoi.",
        "en": "No generation started, because the spending was not confirmed. Launch "
        "`ut init` again whenever you want.",
    },
    "init.errors.SPENDING_REFUSED.answers": {
        "it": "Con --answers non faccio domande, quindi la spesa va confermata con --yes: non "
        "è partita nessuna generazione. Rilancia il comando aggiungendo --yes.",
        "en": "With --answers no question is asked, so the spending must be confirmed with "
        "--yes: no generation started. Launch the command again adding --yes.",
    },
    "init.errors.GENERATION_BUDGET_EXCEEDED": {
        "it": "Lo Studio ha rifiutato la generazione perché supererebbe un tetto di spesa. "
        "Chi gestisce lo Studio può alzarlo; poi rilancia `ut init`, che riprende da qui.",
        "en": "The Studio refused the generation because it would go over a spending "
        "ceiling. Whoever runs the Studio can raise it; then launch `ut init` again, and it "
        "resumes from here.",
    },
    "init.errors.GENERATION_BUDGET_EXCEEDED.total": {
        "it": "Lo Studio ha raggiunto il suo tetto di spesa complessivo ({ceiling} USD): la "
        "generazione non è partita. Chi gestisce lo Studio può alzarlo; poi rilancia "
        "`ut init`, che riprende da qui.",
        "en": "The Studio reached its overall spending ceiling ({ceiling} USD): the "
        "generation did not start. Whoever runs the Studio can raise it; then launch "
        "`ut init` again, and it resumes from here.",
    },
    "init.errors.GENERATION_BUDGET_EXCEEDED.project": {
        "it": "Questo progetto ha raggiunto il suo tetto di spesa ({ceiling} USD): la "
        "generazione non è partita. Chi gestisce lo Studio può alzarlo; poi rilancia "
        "`ut init`, che riprende da qui.",
        "en": "This project reached its spending ceiling ({ceiling} USD): the generation did "
        "not start. Whoever runs the Studio can raise it; then launch `ut init` again, and it "
        "resumes from here.",
    },
    "init.errors.GENERATION_BUDGET_EXCEEDED.generation": {
        "it": "Questa generazione supererebbe il tetto di spesa di una singola generazione "
        "({ceiling} USD), quindi non è partita. Chi gestisce lo Studio può alzarlo; poi "
        "rilancia `ut init`, che riprende da qui.",
        "en": "This generation would go over the spending ceiling of a single generation "
        "({ceiling} USD), so it did not start. Whoever runs the Studio can raise it; then "
        "launch `ut init` again, and it resumes from here.",
    },
    "init.errors.TOO_MANY_GENERATIONS": {
        "it": "{label}: nello Studio girano ancora troppe generazioni dopo otto attese. "
        "Aspetta che qualcuna finisca, poi rilancia `ut init`, che riprende da qui.",
        "en": "{label}: too many generations are still running in the Studio after eight "
        "waits. Wait for some to finish, then launch `ut init` again, and it resumes from "
        "here.",
    },
    "init.errors.GENERATION_FAILED": {
        "it": "{label}: la generazione non è riuscita ({code}). Quello che hai approvato è "
        "salvato: rilancia `ut init` per riprovare, sapendo che è una nuova spesa.",
        "en": "{label}: the generation did not succeed ({code}). What you approved is saved: "
        "launch `ut init` again to try once more, knowing that it is a new expense.",
    },
    "init.errors.GENERATION_LOST": {
        "it": "{label}: la generazione si è persa, forse perché lo Studio è ripartito. Quello "
        "che hai approvato è salvato: rilancia `ut init`, che riprende da questo passo (una "
        "nuova generazione è una nuova spesa).",
        "en": "{label}: the generation was lost, perhaps because the Studio restarted. What "
        "you approved is saved: launch `ut init` again, and it resumes from this step (a new "
        "generation is a new expense).",
    },
    "init.errors.GENERATION_STILL_RUNNING": {
        "it": "{label}: la generazione continua nello Studio. Rilancia `ut init` più tardi: "
        "la ritrova e riprende da lì.",
        "en": "{label}: the generation goes on in the Studio. Launch `ut init` again later: "
        "it finds it and resumes from there.",
    },
    "init.errors.GENERATION_INTERRUPTED": {
        "it": "Interrotto. {label}: la generazione continua nello Studio; rilanciando "
        "`ut init` la ritrovi.",
        "en": "Interrupted. {label}: the generation goes on in the Studio; launching "
        "`ut init` again finds it.",
    },
    "init.errors.STATE_CHANGED": {
        "it": "Il progetto continua a cambiare mentre ut init lavora ({code}): forse è aperto "
        "anche nell'interfaccia web. Finisci lì le modifiche, poi rilancia `ut init`.",
        "en": "The project keeps changing while ut init works ({code}): perhaps it is open in "
        "the web interface too. Finish the changes there, then launch `ut init` again.",
    },
    "init.errors.GATE_REFUSED": {
        "it": "Lo Studio non accetta l'approvazione del passo «{step}» ({code}). Apri il "
        "progetto nell'interfaccia web per vedere perché.",
        "en": 'The Studio does not accept the approval of the step "{step}" ({code}). Open the '
        "project in the web interface to see why.",
    },
    "init.errors.BRIEF_INCOMPLETE": {
        "it": "Il brief non si può approvare, mancano questi punti: {fields}. Rilancia "
        "`ut init` per correggerli.",
        "en": "The brief cannot be approved, these points are missing: {fields}. Launch "
        "`ut init` again to correct them.",
    },
    "init.errors.PROJECT_ALREADY_LINKED": {
        "it": "La cartella {root} è già collegata a un altro progetto dello Studio: --project "
        "non può collegarla a un secondo. Usa una cartella nuova.",
        "en": "The folder {root} is already linked to another project of the Studio: "
        "--project cannot link it to a second one. Use a new folder.",
    },
    "init.errors.NAME_INVALID": {
        "it": "Il nome del progetto deve avere da 1 a {limit} caratteri.",
        "en": "The name of the project must have from 1 to {limit} characters.",
    },
    "init.errors.IDEA_INVALID": {
        "it": "L'idea deve avere da 1 a {limit} caratteri.",
        "en": "The idea must have from 1 to {limit} characters.",
    },
    "init.errors.PROJECT_ID_INVALID": {
        "it": "«{value}» non è l'identificativo di un progetto: lo trovi nell'indirizzo "
        "della pagina del progetto nell'interfaccia web.",
        "en": '"{value}" is not the identifier of a project: you find it in the address of '
        "the page of the project in the web interface.",
    },
    "init.errors.TEAM_BLOCKED": {
        "it": "Le prospettive non si possono preparare: il brief chiede ed esclude insieme "
        "{names}.{details} Correggi il brief nello Studio web (passo Brief, «Modifica il brief "
        "di persona»), poi rilancia `ut init`.",
        "en": "The perspectives cannot be prepared: the brief both asks for and rules out "
        '{names}.{details} Correct the brief in the web Studio (step Brief, "Edit the brief '
        'yourself"), then launch `ut init` again.',
    },
    "init.errors.NO_PROFILE_CONFIRMED": {
        "it": "Nessun archetipo è confermato, quindi gli User Twin non si possono "
        "creare. Apri il progetto nell'interfaccia web per rivedere gli archetipi.",
        "en": "No archetype is confirmed, so the User Twins cannot be created. Open the "
        "project in the web interface to review the archetypes.",
    },
    "init.errors.ANSWERS_FILE_INVALID": {
        "it": "Il file delle risposte {path} non è valido (`{entry}`).",
        "en": "The answers file {path} is not valid (`{entry}`).",
    },
    "init.errors.ANSWERS_FILE_INVALID.unreadable": {
        "it": "Non riesco a leggere il file delle risposte {path}: controlla che esista e che "
        "non superi 1 MB.",
        "en": "The answers file {path} cannot be read: check that it exists and that it is "
        "not larger than 1 MB.",
    },
    "init.errors.ANSWERS_FILE_INVALID.not_json": {
        "it": "Il file delle risposte {path} non è un documento JSON valido in UTF-8.",
        "en": "The answers file {path} is not a valid JSON document in UTF-8.",
    },
    "init.errors.ANSWERS_FILE_INVALID.not_object": {
        "it": "Il file delle risposte {path} deve contenere un oggetto JSON, tra parentesi graffe.",
        "en": "The answers file {path} must hold a JSON object, between curly brackets.",
    },
    "init.errors.ANSWERS_FILE_INVALID.unknown_key": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` non esiste. Le chiavi "
        "possibili qui sono: {allowed}.",
        "en": "In the answers file {path} the key `{entry}` does not exist. The possible keys "
        "here are: {allowed}.",
    },
    "init.errors.ANSWERS_FILE_INVALID.choice": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` vale {value}, ma deve essere "
        "uno di questi valori: {allowed}.",
        "en": "In the answers file {path} the key `{entry}` is {value}, but it must be one of "
        "these values: {allowed}.",
    },
    "init.errors.ANSWERS_FILE_INVALID.text": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` deve essere un testo non "
        "vuoto di al massimo {limit} caratteri.",
        "en": "In the answers file {path} the key `{entry}` must be a text that is not empty, "
        "of at most {limit} characters.",
    },
    "init.errors.ANSWERS_FILE_INVALID.texts": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` deve essere un testo oppure "
        "un elenco di testi, non vuoti e non troppo lunghi.",
        "en": "In the answers file {path} the key `{entry}` must be a text or a list of texts, "
        "not empty and not too long.",
    },
    "init.errors.ANSWERS_FILE_INVALID.object": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` deve essere un oggetto JSON, "
        "tra parentesi graffe.",
        "en": "In the answers file {path} the key `{entry}` must be a JSON object, between "
        "curly brackets.",
    },
    "init.errors.ANSWERS_FILE_INVALID.missing": {
        "it": "Nel file delle risposte {path} manca la chiave `{entry}`, che serve per creare un "
        "progetto nuovo: aggiungila, oppure usa l'opzione --{entry}.",
        "en": "The answers file {path} lacks the key `{entry}`, which is needed to create a new "
        "project: add it, or use the option --{entry}.",
    },
}
