from __future__ import annotations

MESSAGES: dict[str, dict[str, str]] = {
    "init.help": {
        "it": "Crea un progetto e lo porta dall'idea ai requisiti approvati",
        "en": "Create a project and take it from the idea to approved requirements",
    },
    "init.option_name": {"it": "nome del progetto", "en": "name of the project"},
    "init.option_idea": {
        "it": "l'idea, in una o due frasi",
        "en": "the idea, in one or two sentences",
    },
    "init.option_mode": {
        "it": "design: solo design (predefinito); design-code: design e poi codice",
        "en": "design: design only (default); design-code: design and then code",
    },
    "init.option_project": {
        "it": "collega questa cartella a un progetto che esiste già nello Studio",
        "en": "link this folder to a project that already exists in the Studio",
    },
    "init.option_answers": {
        "it": "file JSON con le risposte, per fare tutto il percorso senza domande",
        "en": "JSON file with the answers, to run the whole path without questions",
    },
    "init.option_until": {
        "it": "si ferma dopo il passo indicato: brief, team, twins oppure requirements",
        "en": "stop after the named step: brief, team, twins or requirements",
    },
    "init.welcome": {
        "it": "Nuovo progetto di OrchesTwin in questa cartella.",
        "en": "New OrchesTwin project in this folder.",
    },
    "init.path": {
        "it": "Il percorso ha quattro passi: il brief, la squadra, gli User Twin e i requisiti. "
        "Lo Studio prepara ogni passo con il suo modello e tu lo approvi qui; quello che "
        "approvi resta salvato anche se ti fermi a metà.",
        "en": "The path has four steps: the brief, the team, the User Twins and the "
        "requirements. The Studio prepares each step with its model and you approve it here; "
        "what you approve stays saved even if you stop halfway.",
    },
    "init.mode_question": {"it": "Come vuoi lavorare?", "en": "How do you want to work?"},
    "init.mode_design_only": {
        "it": "Solo design (consigliato): arrivi a un design approvato",
        "en": "Design only (recommended): you get to an approved design",
    },
    "init.mode_design_and_code": {
        "it": "Design e codice: dopo il design, un comando successivo genera il codice",
        "en": "Design and code: after the design, a later command generates the code",
    },
    "init.mode_code_note": {
        "it": "Il codice lo genererà un comando successivo: anche in questa modalità il "
        "percorso parte dal design.",
        "en": "The code will be generated by a later command: in this mode too the path "
        "starts from the design.",
    },
    "init.mode_updated": {
        "it": "Modalità del progetto aggiornata: {mode}.",
        "en": "Mode of the project updated: {mode}.",
    },
    "init.idea": {
        "it": "Racconta la tua idea in una o due righe: che cosa vuoi realizzare, e per chi?",
        "en": "Tell your idea in one or two lines: what do you want to build, and for whom?",
    },
    "init.idea_required": {
        "it": "Serve almeno una riga con l'idea per partire.",
        "en": "At least one line with the idea is needed to start.",
    },
    "init.idea_too_long": {
        "it": "L'idea è troppo lunga: scrivila in al massimo {limit} caratteri.",
        "en": "The idea is too long: write it in at most {limit} characters.",
    },
    "init.name": {"it": "Nome del progetto:", "en": "Name of the project:"},
    "init.name_too_long": {
        "it": "Il nome deve avere al massimo {limit} caratteri.",
        "en": "The name must have at most {limit} characters.",
    },
    "init.created": {
        "it": 'Progetto "{name}" creato nello Studio. Il collegamento con questa cartella è '
        "in {path}.",
        "en": 'Project "{name}" created in the Studio. The link with this folder is in {path}.',
    },
    "init.attaching": {
        "it": 'Collego questa cartella al progetto "{name}" dello Studio.',
        "en": 'Linking this folder to the project "{name}" of the Studio.',
    },
    "init.linked": {
        "it": 'Cartella collegata al progetto "{name}": il collegamento è in {path}.',
        "en": 'Folder linked to the project "{name}": the link is in {path}.',
    },
    "init.resume": {
        "it": 'Riprendo il progetto "{name}" dal passo {number} di {total}: {step}.',
        "en": 'Resuming the project "{name}" from step {number} of {total}: {step}.',
    },
    "init.resume_done": {
        "it": 'Il progetto "{name}" ha già brief, squadra, User Twin e requisiti approvati.',
        "en": 'The project "{name}" already has an approved brief, team, User Twins and '
        "requirements.",
    },
    "init.state_changed": {
        "it": "Il progetto è cambiato nel frattempo, forse dall'interfaccia web ({code}): "
        "rileggo lo stato e continuo da lì.",
        "en": "The project changed in the meantime, perhaps from the web interface ({code}): "
        "reading its state again and going on from there.",
    },
    "init.step_heading": {
        "it": "Passo {number} di {total}: {step}",
        "en": "Step {number} of {total}: {step}",
    },
    "init.already_approved": {
        "it": 'Passo "{step}" già approvato (versione {version}).',
        "en": 'Step "{step}" already approved (version {version}).',
    },
    "init.step_approved": {
        "it": 'Passo "{step}" approvato (versione {version}). Salvato in {path}.',
        "en": 'Step "{step}" approved (version {version}). Saved in {path}.',
    },
    "init.folder_updated": {
        "it": "Cartella di conoscenza aggiornata in orchestwin/ (versione {version}): contiene i "
        "passi approvati finora.",
        "en": "Knowledge folder updated in orchestwin/ (version {version}): it holds the steps "
        "approved so far.",
    },
    "init.folder_not_updated": {
        "it": "La cartella di conoscenza non è stata aggiornata ({code}): il percorso continua, e "
        "puoi scaricarla più tardi con `ut package publish`.",
        "en": "The knowledge folder was not updated ({code}): the path goes on, and you can "
        "download it later with `ut package publish`.",
    },
    "init.until_stop": {
        "it": 'Mi fermo dopo il passo "{step}", come chiesto con --until. Rilancia `ut init` '
        'per continuare con il passo "{next}".',
        "en": 'Stopping after the step "{step}", as asked with --until. Launch `ut init` '
        'again to go on with the step "{next}".',
    },
    "init.done": {
        "it": 'Fatto: il progetto "{name}" ha approvati tutti i passi fino ai requisiti.',
        "en": 'Done: the project "{name}" has every step approved up to the requirements.',
    },
    "init.done_step": {"it": "- {step}: versione {version}", "en": "- {step}: version {version}"},
    "init.done_saved": {
        "it": "Le versioni approvate sono in {steps}; il collegamento con lo Studio è in {link}.",
        "en": "The approved versions are in {steps}; the link with the Studio is in {link}.",
    },
    "init.next_design": {
        "it": "Il prossimo comando è `ut design`: prepara le alternative di design e ti fa "
        "scegliere quella da approvare.",
        "en": "The next command is `ut design`: it prepares the design alternatives and lets "
        "you choose the one to approve.",
    },
    "init.generation_resumed": {
        "it": "{label}: una generazione di questo passo è già in corso nello Studio, la seguo "
        "invece di avviarne un'altra.",
        "en": "{label}: a generation of this step is already running in the Studio; following "
        "it instead of starting another one.",
    },
    "init.busy": {
        "it": "Nello Studio girano già troppe generazioni: aspetto {seconds} secondi e "
        "riprovo (tentativo {attempt} di {attempts}).",
        "en": "Too many generations are already running in the Studio: waiting {seconds} "
        "seconds and trying again (attempt {attempt} of {attempts}).",
    },
    "init.generation_failed": {
        "it": "{label}: il modello non ha dato un risultato valido ({code}).",
        "en": "{label}: the model did not give a valid result ({code}).",
    },
    "init.retry_confirm": {
        "it": "Riprovo una volta? È una nuova generazione, circa {amount} USD.",
        "en": "Try once more? It is a new generation, about {amount} USD.",
    },
    "init.retry_assumed": {
        "it": "Riprovo una volta, perché con --yes hai già confermato la spesa (circa "
        "{amount} USD).",
        "en": "Trying once more, because with --yes you already confirmed the spending "
        "(about {amount} USD).",
    },
    "init.dialogue_starting": {
        "it": "L'analista delle esigenze legge l'idea e prepara la prima domanda...",
        "en": "The needs analyst reads the idea and prepares the first question...",
    },
    "init.dialogue_label": {"it": "Dialogo del brief", "en": "Dialogue of the brief"},
    "init.dialogue_intro": {
        "it": "Ti faccio qualche domanda sull'idea, una alla volta. Quando rispondi:",
        "en": "I will ask a few questions about the idea, one at a time. When you answer:",
    },
    "init.dialogue_rule_unknown": {
        "it": '- una risposta vuota oppure ? vuol dire "non lo so, proponilo tu";',
        "en": '- an empty answer or ? means "I do not know, propose it yourself";',
    },
    "init.dialogue_rule_done": {
        "it": "- /fine compone il brief con quello che hai detto finora (va bene anche /done);",
        "en": "- /done composes the brief with what you said so far (/fine works too);",
    },
    "init.dialogue_rule_quit": {
        "it": "- /esci chiude ut init: rilanciandolo riprendi da questa domanda (va bene anche "
        "/quit).",
        "en": "- /quit closes ut init: launching it again resumes from this question (/esci "
        "works too).",
    },
    "init.dialogue_open": {
        "it": "Punti essenziali ancora aperti: {count}.",
        "en": "Essential points still open: {count}.",
    },
    "init.dialogue_question": {
        "it": "Domanda {number}: {question}",
        "en": "Question {number}: {question}",
    },
    "init.dialogue_list_hint": {
        "it": "Scrivi un elemento per riga; una riga vuota conclude.",
        "en": "Write one item per line; an empty line ends the list.",
    },
    "init.dialogue_answer": {"it": "Risposta:", "en": "Answer:"},
    "init.answer_too_many": {
        "it": "Sono troppi elementi: al massimo {limit}. Riprova.",
        "en": "Too many items: at most {limit}. Try again.",
    },
    "init.answer_too_long": {
        "it": "La risposta è troppo lunga: al massimo {limit} caratteri. Riprova.",
        "en": "The answer is too long: at most {limit} characters. Try again.",
    },
    "init.dialogue_essentials_done": {
        "it": "Il brief ha già tutti i punti essenziali.",
        "en": "The brief already has every essential point.",
    },
    "init.dialogue_more": {
        "it": "Vuoi rispondere ad altre domande per renderlo più preciso, o comporlo adesso?",
        "en": "Do you want to answer more questions to make it more precise, or compose it now?",
    },
    "init.dialogue_more_yes": {
        "it": "Rispondo ad altre domande (con /fine lo componi quando vuoi)",
        "en": "Answer more questions (/done composes it whenever you want)",
    },
    "init.dialogue_more_no": {"it": "Componi il brief adesso", "en": "Compose the brief now"},
    "init.dialogue_scripted": {
        "it": "Risposta dal file: {answer}",
        "en": "Answer from the file: {answer}",
    },
    "init.dialogue_scripted_unknown": {
        "it": "Risposta dal file: non lo so, lo propone il modello.",
        "en": "Answer from the file: I do not know, the model proposes it.",
    },
    "init.dialogue_ready": {
        "it": "Le domande sono finite: compongo il brief.",
        "en": "The questions are over: composing the brief.",
    },
    "init.dialogue_left": {
        "it": "Ti fermi qui: il dialogo resta aperto nello Studio. Rilancia `ut init` per "
        "riprendere da questa domanda.",
        "en": "You stop here: the dialogue stays open in the Studio. Launch `ut init` again to "
        "resume from this question.",
    },
    "init.compose_label": {"it": "Compongo il brief", "en": "Composing the brief"},
    "init.compose_unchanged": {
        "it": "Il brief composto è uguale alla versione che c'è già: tengo quella.",
        "en": "The composed brief is the same as the version already there: keeping that one.",
    },
    "init.dialogue_unavailable": {
        "it": "Lo Studio non ha un modello per il dialogo del brief "
        "(BRIEF_DIALOGUE_MODEL_NOT_CONFIGURED): ti chiedo io i punti essenziali. Quello che "
        "lasci vuoto resta un punto aperto.",
        "en": "The Studio has no model for the dialogue of the brief "
        "(BRIEF_DIALOGUE_MODEL_NOT_CONFIGURED): I ask you the essential points myself. What "
        "you leave empty stays an open point.",
    },
    "init.question_problem": {
        "it": "Quale problema risolve il progetto?",
        "en": "Which problem does the project solve?",
    },
    "init.question_target_users": {
        "it": "Chi userà il prodotto?",
        "en": "Who will use the product?",
    },
    "init.question_goals": {
        "it": "Quali risultati vuoi ottenere?",
        "en": "Which results do you want to reach?",
    },
    "init.question_functional_requirements": {
        "it": "Che cosa deve permettere di fare il prodotto?",
        "en": "What must the product let people do?",
    },
    "init.manual_left": {
        "it": "Ti fermi qui: del brief non ho salvato nulla. Rilancia `ut init` per "
        "ricominciare da queste domande.",
        "en": "You stop here: nothing of the brief was saved. Launch `ut init` again to start "
        "again from these questions.",
    },
    "init.manual_saved": {
        "it": "Brief salvato nello Studio (versione {version}).",
        "en": "Brief saved in the Studio (version {version}).",
    },
    "init.brief_heading": {
        "it": "Il brief (versione {version}):",
        "en": "The brief (version {version}):",
    },
    "init.brief_open": {
        "it": "Punti aperti, ancora da decidere: {fields}.",
        "en": "Open points, still to decide: {fields}.",
    },
    "init.proposals_intro": {
        "it": "Proposte del modello per i punti che non hai deciso: {count}.",
        "en": "Proposals of the model for the points you did not decide: {count}.",
    },
    "init.proposals_choice": {
        "it": "Che cosa fai con queste proposte?",
        "en": "What do you do with these proposals?",
    },
    "init.proposals_all": {"it": "Le accetto tutte", "en": "Accept them all"},
    "init.proposals_each": {"it": "Decido una per una", "en": "Decide one by one"},
    "init.proposals_none": {
        "it": "Non ne accetto nessuna: restano punti aperti",
        "en": "Accept none: they stay open points",
    },
    "init.proposal_accept": {
        "it": "Accetti la proposta {number} ({field})?",
        "en": "Do you accept proposal {number} ({field})?",
    },
    "init.proposal_reason": {
        "it": "Non accettata dal titolare del progetto con ut init.",
        "en": "Not accepted by the owner of the project with ut init.",
    },
    "init.proposal_skipped": {
        "it": "La proposta {number} non si può più decidere: quel punto è già definito.",
        "en": "Proposal {number} can no longer be decided: that point is already defined.",
    },
    "init.proposals_done": {
        "it": "Proposte accettate: {accepted}; scartate: {rejected}. Il brief è alla "
        "versione {version}.",
        "en": "Proposals accepted: {accepted}; discarded: {rejected}. The brief is at "
        "version {version}.",
    },
    "init.brief_choice": {
        "it": "Che cosa fai con il brief?",
        "en": "What do you do with the brief?",
    },
    "init.brief_approve": {"it": "Lo approvo e vado avanti", "en": "Approve it and go on"},
    "init.brief_correct": {"it": "Correggo un punto", "en": "Correct a point"},
    "init.brief_stop": {"it": "Mi fermo qui", "en": "Stop here"},
    "init.brief_left": {
        "it": "Il brief resta in attesa della tua approvazione. Rilancia `ut init` per "
        "riprendere da qui.",
        "en": "The brief stays waiting for your approval. Launch `ut init` again to resume "
        "from here.",
    },
    "init.brief_incomplete": {
        "it": "Per approvare il brief mancano ancora questi punti: {fields}. Correggili, "
        "oppure scrivi ? per lasciarli aperti.",
        "en": "To approve the brief these points are still missing: {fields}. Correct them, "
        "or write ? to leave them open.",
    },
    "init.correct_which": {
        "it": "Quale punto vuoi correggere?",
        "en": "Which point do you want to correct?",
    },
    "init.correct_text": {
        "it": 'Nuovo valore per "{field}" (? per lasciarlo aperto, riga vuota per annullare):',
        "en": 'New value for "{field}" (? to leave it open, empty line to cancel):',
    },
    "init.correct_list": {
        "it": 'Nuovi elementi per "{field}", uno per riga; una riga vuota conclude. Scrivi ? '
        "per lasciarlo aperto, oppure subito una riga vuota per annullare.",
        "en": 'New items for "{field}", one per line; an empty line ends the list. Write ? to '
        "leave it open, or an empty line at once to cancel.",
    },
    "init.correct_cancelled": {
        "it": "Nessuna correzione: il brief resta com'era.",
        "en": "No correction: the brief stays as it was.",
    },
    "init.correct_saved": {
        "it": "Correzione salvata: il brief è alla versione {version}.",
        "en": "Correction saved: the brief is at version {version}.",
    },
    "init.correct_same": {
        "it": "Il valore è quello di prima: il brief non cambia.",
        "en": "The value is the same as before: the brief does not change.",
    },
    "init.field_name": {"it": "Nome", "en": "Name"},
    "init.field_description": {"it": "L'idea", "en": "The idea"},
    "init.field_problem": {"it": "Il problema", "en": "The problem"},
    "init.field_goals": {"it": "Obiettivi", "en": "Goals"},
    "init.field_target_users": {"it": "Per chi", "en": "For whom"},
    "init.field_domain": {"it": "Contesto", "en": "Context"},
    "init.field_technical_constraints": {"it": "Vincoli tecnici", "en": "Technical constraints"},
    "init.field_temporal_constraints": {"it": "Tempi", "en": "Timing"},
    "init.field_budget": {"it": "Budget", "en": "Budget"},
    "init.field_functional_requirements": {"it": "Cosa deve fare", "en": "What it must do"},
    "init.field_non_functional_requirements": {
        "it": "Qualità attese",
        "en": "Expected qualities",
    },
    "init.field_risks": {"it": "Rischi", "en": "Risks"},
    "init.field_stakeholders": {"it": "Persone coinvolte", "en": "People involved"},
    "init.field_available_artifacts": {
        "it": "Materiali disponibili",
        "en": "Available materials",
    },
    "init.field_definition_of_done": {"it": "Quando sarà finito", "en": "When it is done"},
    "init.designer_missing_end": {
        "it": "Attenzione: la squadra approvata di questo progetto non ha il Designer UX/UI, "
        "quindi le alternative di design non si possono preparare finché la squadra non lo "
        "avrà. La squadra si cambia e si approva di nuovo nello Studio web.",
        "en": "Note: the approved team of this project has no UX/UI designer, so the design "
        "alternatives cannot be prepared until the team has it. The team is changed and "
        "approved again in the web Studio.",
    },
    "init.team_label": {"it": "Propongo la squadra", "en": "Proposing the team"},
    "init.team_heading": {
        "it": "La squadra (versione {version}). Specialisti: {count}.",
        "en": "The team (version {version}). Specialists: {count}.",
    },
    "init.team_why": {"it": "Perché: {reason}", "en": "Why: {reason}"},
    "init.team_platform": {
        "it": "Sempre presenti, per far funzionare lo Studio: {names}.",
        "en": "Always present, to run the Studio: {names}.",
    },
    "init.team_choice": {
        "it": "Che cosa fai con la squadra?",
        "en": "What do you do with the team?",
    },
    "init.team_approve": {"it": "La approvo e vado avanti", "en": "Approve it and go on"},
    "init.team_change": {
        "it": "Cambio gli specialisti della squadra",
        "en": "Change the specialists of the team",
    },
    "init.team_stop": {"it": "Mi fermo qui", "en": "Stop here"},
    "init.team_left": {
        "it": "La squadra resta in attesa della tua approvazione. Rilancia `ut init` per "
        "riprendere da qui.",
        "en": "The team stays waiting for your approval. Launch `ut init` again to resume "
        "from here.",
    },
    "init.team_nothing": {
        "it": "In questo progetto nessuno specialista si può aggiungere o togliere.",
        "en": "No specialist can be added or removed in this project.",
    },
    "init.team_fixed": {
        "it": "Restano sempre nella squadra, perché sono membri obbligatori: {names}.",
        "en": "Always in the team, because they are mandatory members: {names}.",
    },
    "init.team_excluded": {
        "it": "Non possono entrare, per come è scritto il brief: {names}.",
        "en": "Cannot join, the way the brief is written: {names}.",
    },
    "init.team_switch_intro": {
        "it": "Specialisti che puoi aggiungere [ ] o togliere [x]:",
        "en": "Specialists you can add [ ] or remove [x]:",
    },
    "init.team_switch": {
        "it": "Numeri da cambiare, separati da spazi (riga vuota per non cambiare nulla):",
        "en": "Numbers to switch, separated by spaces (empty line to change nothing):",
    },
    "init.team_switch_invalid": {
        "it": "Scrivi solo numeri da 1 a {count}, separati da spazi.",
        "en": "Write only numbers from 1 to {count}, separated by spaces.",
    },
    "init.team_add_reason": {
        "it": 'Perché aggiungi "{name}"? Una riga, resta scritta con la squadra:',
        "en": 'Why do you add "{name}"? One line, it stays written with the team:',
    },
    "init.team_unchanged": {"it": "La squadra non cambia.", "en": "The team does not change."},
    "init.team_updated": {
        "it": "Squadra aggiornata (versione {version}).",
        "en": "Team updated (version {version}).",
    },
    "init.team_owner_reason": {"it": "aggiunto da te: {reason}", "en": "added by you: {reason}"},
    "init.team_issue": {
        "it": "{name}: il cambio non è accettato ({code}).",
        "en": "{name}: the change is not accepted ({code}).",
    },
    "init.team_issue_duplicate_agent": {
        "it": "{name} compare due volte nella scelta.",
        "en": "{name} appears twice in the selection.",
    },
    "init.team_issue_duplicate_rationale": {
        "it": "Per {name} ci sono due motivazioni: ne basta una.",
        "en": "{name} has two reasons: one is enough.",
    },
    "init.team_issue_mandatory_agent_missing": {
        "it": "{name} non si può togliere: è un membro obbligatorio della squadra.",
        "en": "{name} cannot be removed: it is a mandatory member of the team.",
    },
    "init.team_issue_agent_not_selectable": {
        "it": "{name} non può entrare in questa squadra.",
        "en": "{name} cannot join this team.",
    },
    "init.team_issue_rationale_required": {
        "it": "Per aggiungere {name} serve una motivazione.",
        "en": "Adding {name} needs a reason.",
    },
    "init.team_issue_unused_rationale": {
        "it": "La motivazione per {name} non serve: non è un'aggiunta.",
        "en": "The reason for {name} is not needed: it is not an addition.",
    },
    "init.team_blocked": {
        "it": "{name}: il brief lo esclude ({excluded}) e insieme lo richiede ({required}).",
        "en": "{name}: the brief rules it out ({excluded}) and also calls for it ({required}).",
    },
    "init.team_blocked_evidence": {"it": "{terms} in {fields}", "en": "{terms} in {fields}"},
    "init.team_blocked_term": {"it": "«{term}»", "en": "«{term}»"},
    "init.reason_catalog_always_present": {
        "it": "componente sempre presente dello Studio",
        "en": "always-present component of the Studio",
    },
    "init.reason_catalog_mode_incompatible": {
        "it": "non adatto alla modalità del progetto",
        "en": "not suited to the mode of the project",
    },
    "init.reason_core_requirements_discipline": {
        "it": "serve sempre per scrivere requisiti chiari",
        "en": "always needed to write clear requirements",
    },
    "init.reason_core_user_centered_design": {
        "it": "serve sempre per progettare pensando agli utenti",
        "en": "always needed to design around the users",
    },
    "init.reason_core_architecture_discipline": {
        "it": "serve sempre per tenere insieme requisiti e design",
        "en": "always needed to keep requirements and design together",
    },
    "init.reason_core_quality_discipline": {
        "it": "serve sempre per verificare la qualità",
        "en": "always needed to check the quality",
    },
    "init.reason_core_accessibility_discipline": {
        "it": "L'accessibilità fa parte di ogni progetto",
        "en": "Accessibility is part of every project",
    },
    "init.reason_brownfield_integration": {
        "it": "il progetto parte da un sistema che esiste già",
        "en": "the project starts from a system that already exists",
    },
    "init.reason_user_interface_signal": {
        "it": "il brief chiede un'interfaccia per le persone",
        "en": "the brief asks for an interface for people",
    },
    "init.reason_web_delivery_signal": {
        "it": "il brief chiede un prodotto sul web",
        "en": "the brief asks for a product on the web",
    },
    "init.reason_backend_delivery_signal": {
        "it": "il brief chiede dati e servizi dietro le schermate",
        "en": "the brief asks for data and services behind the screens",
    },
    "init.reason_mobile_delivery_signal": {
        "it": "il brief chiede un prodotto per telefoni e tablet",
        "en": "the brief asks for a product for phones and tablets",
    },
    "init.reason_external_integration_signal": {
        "it": "il brief chiede collegamenti con altri servizi",
        "en": "the brief asks for connections with other services",
    },
    "init.reason_security_sensitivity_signal": {
        "it": "il brief tratta dati o accessi delicati",
        "en": "the brief handles sensitive data or access",
    },
    "init.reason_accessibility_requirement_signal": {
        "it": "il brief chiede attenzione all'accessibilità",
        "en": "the brief asks for attention to accessibility",
    },
    "init.reason_explicit_scope_exclusion": {
        "it": "il brief esclude questo ruolo",
        "en": "the brief excludes this role",
    },
    "init.reason_unknown": {"it": "scelto per il progetto", "en": "chosen for the project"},
    "init.agent_workflow_orchestrator": {"it": "Coordinatore", "en": "Coordinator"},
    "init.agent_workflow_orchestrator_role": {
        "it": "Organizza il lavoro e accompagna il progetto da un passo al successivo.",
        "en": "Organizes the work and guides the project through each step.",
    },
    "init.agent_intake_clarification_agent": {"it": "Guida del progetto", "en": "Project guide"},
    "init.agent_intake_clarification_agent_role": {
        "it": "Ti aiuta a chiarire l'idea, gli obiettivi e le priorità.",
        "en": "Helps you clarify the idea, goals and priorities.",
    },
    "init.agent_team_selector": {"it": "Organizzatore del team", "en": "Team planner"},
    "init.agent_team_selector_role": {
        "it": "Propone gli specialisti adatti alla tua idea.",
        "en": "Suggests the specialists your idea needs.",
    },
    "init.agent_human_gate_controller": {
        "it": "Referente delle approvazioni",
        "en": "Approval guide",
    },
    "init.agent_human_gate_controller_role": {
        "it": "Aspetta la tua conferma prima di proseguire.",
        "en": "Waits for your confirmation before moving on.",
    },
    "init.agent_artifact_manager": {"it": "Custode delle versioni", "en": "Version keeper"},
    "init.agent_artifact_manager_role": {
        "it": "Conserva proposte, risultati e decisioni per ritrovarli in ogni momento.",
        "en": "Keeps proposals, results and decisions available for review.",
    },
    "init.agent_sandbox_controller": {
        "it": "Responsabile delle prove",
        "en": "Test environment keeper",
    },
    "init.agent_sandbox_controller_role": {
        "it": "Esegue le prove in un ambiente separato dal tuo progetto.",
        "en": "Runs checks in an environment separate from your project.",
    },
    "init.agent_requirements_analyst": {"it": "Analista delle esigenze", "en": "Needs analyst"},
    "init.agent_requirements_analyst_role": {
        "it": "Trasforma il brief in requisiti chiari, con un modo per verificarli.",
        "en": "Turns the brief into clear requirements, each with a way to check it.",
    },
    "init.agent_ux_researcher_user_modeler": {
        "it": "Ricercatore degli utenti",
        "en": "User researcher",
    },
    "init.agent_ux_researcher_user_modeler_role": {
        "it": "Costruisce i twin e raccoglie le loro critiche.",
        "en": "Builds the twins and gathers their critiques.",
    },
    "init.agent_ux_ui_designer": {"it": "Designer UX/UI", "en": "UX/UI designer"},
    "init.agent_ux_ui_designer_role": {
        "it": "Propone le alternative di design e i mockup navigabili.",
        "en": "Proposes the design alternatives and the clickable mockups.",
    },
    "init.agent_software_architect": {"it": "Architetto del prodotto", "en": "Product architect"},
    "init.agent_software_architect_role": {
        "it": "Controlla che requisiti e design stiano in piedi insieme.",
        "en": "Checks that requirements and design hold together.",
    },
    "init.agent_frontend_engineer": {
        "it": "Sviluppatore dell'interfaccia",
        "en": "Interface developer",
    },
    "init.agent_frontend_engineer_role": {
        "it": "Prepara il pacchetto per chi costruirà le schermate.",
        "en": "Prepares the package for whoever builds the screens.",
    },
    "init.agent_backend_engineer": {"it": "Sviluppatore dei servizi", "en": "Service developer"},
    "init.agent_backend_engineer_role": {
        "it": "Gestisce dati e funzioni che lavorano dietro le schermate.",
        "en": "Builds the data and features behind the screens.",
    },
    "init.agent_mobile_engineer": {"it": "Sviluppatore mobile", "en": "Mobile developer"},
    "init.agent_mobile_engineer_role": {
        "it": "Realizza l'esperienza per telefoni e tablet.",
        "en": "Builds the experience for phones and tablets.",
    },
    "init.agent_qa_test_engineer": {"it": "Specialista della qualità", "en": "Quality specialist"},
    "init.agent_qa_test_engineer_role": {
        "it": 'Scrive come controllare ogni requisito prima di dire "finito".',
        "en": "Writes how to check each requirement before calling it done.",
    },
    "init.agent_security_reviewer": {
        "it": "Specialista della sicurezza",
        "en": "Security specialist",
    },
    "init.agent_security_reviewer_role": {
        "it": "Controlla accessi, riservatezza e protezione dei dati.",
        "en": "Reviews access, privacy and data protection.",
    },
    "init.agent_accessibility_reviewer": {
        "it": "Specialista dell'accessibilità",
        "en": "Accessibility specialist",
    },
    "init.agent_accessibility_reviewer_role": {
        "it": "Rivede contrasto, uso da tastiera e leggibilità dei mockup.",
        "en": "Reviews contrast, keyboard use and readability of the mockups.",
    },
    "init.agent_integration_engineer": {
        "it": "Specialista dei collegamenti",
        "en": "Integration specialist",
    },
    "init.agent_integration_engineer_role": {
        "it": "Collega il prodotto agli altri servizi di cui hai bisogno.",
        "en": "Connects your product to the other services it needs.",
    },
    "init.profiles_label": {
        "it": "Propongo i profili degli utenti",
        "en": "Proposing the user profiles",
    },
    "init.profiles_intro": {
        "it": "Profili di utenti tipo proposti dal modello: {count}. Per ciascuno scegli se "
        "confermarlo o scartarlo: dai profili confermati nascono gli User Twin.",
        "en": "Profiles of typical users proposed by the model: {count}. For each one, choose "
        "whether to confirm or discard it: the User Twins are made from the confirmed profiles.",
    },
    "init.profile_heading": {
        "it": "Profilo {number} di {total}: {name}",
        "en": "Profile {number} of {total}: {name}",
    },
    "init.profile_confirmed": {
        "it": "Profilo {number} di {total}, {name}: già confermato.",
        "en": "Profile {number} of {total}, {name}: already confirmed.",
    },
    "init.profile_rejected": {
        "it": "Profilo {number} di {total}, {name}: già scartato.",
        "en": "Profile {number} of {total}, {name}: already discarded.",
    },
    "init.profile_confirm": {
        "it": "Confermi questo profilo?",
        "en": "Do you confirm this profile?",
    },
    "init.profile_needed": {
        "it": "Serve almeno un profilo confermato per creare gli User Twin: questo è "
        "l'ultimo, quindi va confermato.",
        "en": "At least one confirmed profile is needed to create the User Twins: this is the "
        "last one, so it has to be confirmed.",
    },
    "init.profile_reason": {
        "it": "Perché lo scarti? Una riga, resta scritta con il profilo:",
        "en": "Why do you discard it? One line, it stays written with the profile:",
    },
    "init.profile_reason_default": {
        "it": "Non rappresenta gli utenti del progetto.",
        "en": "It does not represent the users of the project.",
    },
    "init.twins_label": {
        "it": "Creo gli User Twin dai profili confermati",
        "en": "Creating the User Twins from the confirmed profiles",
    },
    "init.twins_heading": {
        "it": "Gli User Twin (versione {version}). User Twin creati: {count}.",
        "en": "The User Twins (version {version}). User Twins created: {count}.",
    },
    "init.twin_heading": {
        "it": "User Twin {number} di {total}: {name}",
        "en": "User Twin {number} of {total}: {name}",
    },
    "init.detail_role": {"it": "Ruolo", "en": "Role"},
    "init.detail_summary": {"it": "In breve", "en": "In short"},
    "init.detail_goals": {"it": "Obiettivi", "en": "Goals"},
    "init.detail_difficulties": {"it": "Difficoltà", "en": "Difficulties"},
    "init.detail_context": {
        "it": "Dove e come usa il prodotto",
        "en": "Where and how they use the product",
    },
    "init.twins_choice": {
        "it": "Che cosa fai con gli User Twin?",
        "en": "What do you do with the User Twins?",
    },
    "init.twins_approve": {"it": "Li approvo e vado avanti", "en": "Approve them and go on"},
    "init.twins_stop": {"it": "Mi fermo qui", "en": "Stop here"},
    "init.twins_left": {
        "it": "Gli User Twin restano in attesa della tua approvazione. Rilancia `ut init` per "
        "riprendere da qui.",
        "en": "The User Twins stay waiting for your approval. Launch `ut init` again to resume "
        "from here.",
    },
    "init.requirements_wait": {
        "it": "Adesso lo Studio scrive i requisiti a partire dal brief e dagli User Twin: ci "
        "vogliono circa due minuti.",
        "en": "Now the Studio writes the requirements from the brief and the User Twins: it "
        "takes about two minutes.",
    },
    "init.requirements_label": {"it": "Scrivo i requisiti", "en": "Writing the requirements"},
    "init.requirements_heading": {
        "it": "I requisiti (versione {version}). Requisiti: {requirements}; storie degli utenti: "
        "{stories}; criteri di accettazione: {criteria}.",
        "en": "The requirements (version {version}). Requirements: {requirements}; user stories: "
        "{stories}; acceptance criteria: {criteria}.",
    },
    "init.column_code": {"it": "Codice", "en": "Code"},
    "init.column_title": {"it": "Titolo", "en": "Title"},
    "init.column_priority": {"it": "Priorità", "en": "Priority"},
    "init.priority_must": {"it": "indispensabile", "en": "must have"},
    "init.priority_should": {"it": "importante", "en": "should have"},
    "init.priority_could": {"it": "utile", "en": "could have"},
    "init.priority_wont_for_now": {"it": "non per ora", "en": "not for now"},
    "init.kind_functional": {"it": "funzione", "en": "function"},
    "init.kind_non_functional": {"it": "qualità", "en": "quality"},
    "init.kind_constraint": {"it": "vincolo", "en": "constraint"},
    "init.requirements_choice": {
        "it": "Che cosa fai con i requisiti?",
        "en": "What do you do with the requirements?",
    },
    "init.requirements_approve": {"it": "Li approvo e vado avanti", "en": "Approve them and go on"},
    "init.requirements_read": {
        "it": "Li leggo tutti: requisiti, storie e criteri di accettazione",
        "en": "Read them all: requirements, stories and acceptance criteria",
    },
    "init.requirements_change": {
        "it": "Chiedo una modifica a parole",
        "en": "Ask for a change in words",
    },
    "init.requirements_stop": {"it": "Mi fermo qui", "en": "Stop here"},
    "init.requirements_left": {
        "it": "I requisiti restano in attesa della tua approvazione. Rilancia `ut init` per "
        "riprendere da qui.",
        "en": "The requirements stay waiting for your approval. Launch `ut init` again to "
        "resume from here.",
    },
    "init.all_requirements": {"it": "Requisiti", "en": "Requirements"},
    "init.all_stories": {"it": "Storie degli utenti", "en": "User stories"},
    "init.all_criteria": {"it": "Criteri di accettazione", "en": "Acceptance criteria"},
    "init.requirement_line": {
        "it": "{code} {title} ({priority}, {kind})",
        "en": "{code} {title} ({priority}, {kind})",
    },
    "init.story_line": {
        "it": "{code} {twin} vuole {goal}, per {benefit}.",
        "en": "{code} {twin} wants to {goal}, so as to {benefit}.",
    },
    "init.story_someone": {"it": "Un utente", "en": "A user"},
    "init.criterion_check": {"it": "si verifica con {method}", "en": "checked by {method}"},
    "init.verify_automated_test": {"it": "un test automatico", "en": "an automated test"},
    "init.verify_manual_review": {"it": "una revisione a mano", "en": "a manual review"},
    "init.verify_inspection": {"it": "un'ispezione", "en": "an inspection"},
    "init.verify_demonstration": {"it": "una dimostrazione", "en": "a demonstration"},
    "init.verify_analysis": {"it": "un'analisi", "en": "an analysis"},
    "init.change_request": {
        "it": "Scrivi con parole tue che cosa vuoi cambiare nei requisiti (per annullare, "
        "subito una riga vuota).",
        "en": "Write in your own words what you want to change in the requirements (to "
        "cancel, an empty line at once).",
    },
    "init.change_cancelled": {"it": "Nessuna modifica chiesta.", "en": "No change asked."},
    "init.change_scripted": {
        "it": "Modifica chiesta dal file: {request}",
        "en": "Change asked by the file: {request}",
    },
    "init.change_label": {
        "it": "Preparo la modifica dei requisiti",
        "en": "Preparing the change to the requirements",
    },
    "init.change_unchanged": {
        "it": "Lo Studio non ha trovato niente da cambiare con questa richiesta: i requisiti "
        "restano come sono.",
        "en": "The Studio found nothing to change with this request: the requirements stay "
        "as they are.",
    },
    "init.change_waiting": {
        "it": "C'è una modifica dei requisiti proposta e non ancora decisa: eccola.",
        "en": "There is a proposed change to the requirements that is not decided yet: here it is.",
    },
    "init.change_heading": {
        "it": "La modifica proposta. Cambiamenti: {count}.",
        "en": "The proposed change. Changes: {count}.",
    },
    "init.change_add": {
        "it": "+ si aggiunge {what} {code}: {text}",
        "en": "+ adds {what} {code}: {text}",
    },
    "init.change_replace": {
        "it": "~ cambia {what} {code}: {text}",
        "en": "~ changes {what} {code}: {text}",
    },
    "init.change_remove": {
        "it": "- si toglie {what} {code}: {text}",
        "en": "- removes {what} {code}: {text}",
    },
    "init.change_other": {"it": "* {what} {code}: {text}", "en": "* {what} {code}: {text}"},
    "init.artifact_requirement": {"it": "il requisito", "en": "the requirement"},
    "init.artifact_user_story": {"it": "la storia", "en": "the story"},
    "init.artifact_acceptance_criterion": {"it": "il criterio", "en": "the criterion"},
    "init.artifact_scenario": {"it": "lo scenario", "en": "the scenario"},
    "init.artifact_risk": {"it": "il rischio", "en": "the risk"},
    "init.artifact_definition_of_done": {
        "it": "la condizione di fine lavoro",
        "en": "the done condition",
    },
    "init.change_apply": {"it": "Applichi questa modifica?", "en": "Do you apply this change?"},
    "init.change_reason": {
        "it": "Scartata dal titolare del progetto con ut init.",
        "en": "Discarded by the owner of the project with ut init.",
    },
    "init.change_applied": {
        "it": "Modifica applicata: i requisiti sono alla versione {version}.",
        "en": "Change applied: the requirements are at version {version}.",
    },
    "init.change_discarded": {
        "it": "Modifica scartata: i requisiti restano alla versione {version}.",
        "en": "Change discarded: the requirements stay at version {version}.",
    },
    "init.errors.NOT_SIGNED_IN": {
        "it": "Per creare o continuare un progetto serve l'accesso allo Studio {studio}: "
        "accedi con `ut login`, poi rilancia `ut init`.",
        "en": "Creating or continuing a project needs a sign-in to the Studio {studio}: sign "
        "in with `ut login`, then launch `ut init` again.",
    },
    "init.errors.STUDIO_UNREACHABLE": {
        "it": "Lo Studio all'indirizzo {address} non risponde. Non si è perso niente: quello "
        "che hai approvato è salvato. Quando lo Studio torna raggiungibile, rilancia "
        "`ut init` e riprendi da dove eri.",
        "en": "The Studio at {address} does not answer. Nothing is lost: what you approved is "
        "saved. When the Studio can be reached again, launch `ut init` again and resume from "
        "where you were.",
    },
    "init.errors.INPUT_CLOSED": {
        "it": "L'input si è chiuso mentre aspettavo una risposta: non ho fatto altro. Non si è "
        "perso niente: quello che hai approvato è salvato, e rilanciando `ut init` riprendi dal "
        "primo passo non ancora approvato.",
        "en": "The input closed while an answer was awaited: nothing else was done. Nothing is "
        "lost: what you approved is saved, and launching `ut init` again continues from the "
        "first step that is not approved yet.",
    },
    "init.errors.SPENDING_REFUSED": {
        "it": "Non è partita nessuna generazione, perché la spesa non è stata confermata. "
        "Rilancia `ut init` quando vuoi.",
        "en": "No generation started, because the spending was not confirmed. Launch "
        "`ut init` again whenever you want.",
    },
    "init.errors.SPENDING_REFUSED.answers": {
        "it": "Con --answers non faccio domande, quindi la spesa va confermata con --yes: non "
        "è partita nessuna generazione. Rilancia il comando aggiungendo --yes.",
        "en": "With --answers no question is asked, so the spending must be confirmed with "
        "--yes: no generation started. Launch the command again adding --yes.",
    },
    "init.errors.GENERATION_BUDGET_EXCEEDED": {
        "it": "Lo Studio ha rifiutato la generazione perché supererebbe un tetto di spesa. "
        "Chi gestisce lo Studio può alzarlo; poi rilancia `ut init`, che riprende da qui.",
        "en": "The Studio refused the generation because it would go over a spending "
        "ceiling. Whoever runs the Studio can raise it; then launch `ut init` again, and it "
        "resumes from here.",
    },
    "init.errors.GENERATION_BUDGET_EXCEEDED.total": {
        "it": "Lo Studio ha raggiunto il suo tetto di spesa complessivo ({ceiling} USD): la "
        "generazione non è partita. Chi gestisce lo Studio può alzarlo; poi rilancia "
        "`ut init`, che riprende da qui.",
        "en": "The Studio reached its overall spending ceiling ({ceiling} USD): the "
        "generation did not start. Whoever runs the Studio can raise it; then launch "
        "`ut init` again, and it resumes from here.",
    },
    "init.errors.GENERATION_BUDGET_EXCEEDED.project": {
        "it": "Questo progetto ha raggiunto il suo tetto di spesa ({ceiling} USD): la "
        "generazione non è partita. Chi gestisce lo Studio può alzarlo; poi rilancia "
        "`ut init`, che riprende da qui.",
        "en": "This project reached its spending ceiling ({ceiling} USD): the generation did "
        "not start. Whoever runs the Studio can raise it; then launch `ut init` again, and it "
        "resumes from here.",
    },
    "init.errors.GENERATION_BUDGET_EXCEEDED.generation": {
        "it": "Questa generazione supererebbe il tetto di spesa di una singola generazione "
        "({ceiling} USD), quindi non è partita. Chi gestisce lo Studio può alzarlo; poi "
        "rilancia `ut init`, che riprende da qui.",
        "en": "This generation would go over the spending ceiling of a single generation "
        "({ceiling} USD), so it did not start. Whoever runs the Studio can raise it; then "
        "launch `ut init` again, and it resumes from here.",
    },
    "init.errors.TOO_MANY_GENERATIONS": {
        "it": "{label}: nello Studio girano ancora troppe generazioni dopo otto attese. "
        "Aspetta che qualcuna finisca, poi rilancia `ut init`, che riprende da qui.",
        "en": "{label}: too many generations are still running in the Studio after eight "
        "waits. Wait for some to finish, then launch `ut init` again, and it resumes from "
        "here.",
    },
    "init.errors.GENERATION_FAILED": {
        "it": "{label}: la generazione non è riuscita ({code}). Quello che hai approvato è "
        "salvato: rilancia `ut init` per riprovare, sapendo che è una nuova spesa.",
        "en": "{label}: the generation did not succeed ({code}). What you approved is saved: "
        "launch `ut init` again to try once more, knowing that it is a new spending.",
    },
    "init.errors.GENERATION_LOST": {
        "it": "{label}: la generazione si è persa, forse perché lo Studio è ripartito. Quello "
        "che hai approvato è salvato: rilancia `ut init`, che riprende da questo passo (una "
        "nuova generazione è una nuova spesa).",
        "en": "{label}: the generation was lost, perhaps because the Studio restarted. What "
        "you approved is saved: launch `ut init` again, and it resumes from this step (a new "
        "generation is a new spending).",
    },
    "init.errors.GENERATION_STILL_RUNNING": {
        "it": "{label}: la generazione continua nello Studio. Rilancia `ut init` più tardi: "
        "la ritrova e riprende da lì.",
        "en": "{label}: the generation goes on in the Studio. Launch `ut init` again later: "
        "it finds it and resumes from there.",
    },
    "init.errors.GENERATION_INTERRUPTED": {
        "it": "Interrotto. {label}: la generazione continua nello Studio; rilanciando "
        "`ut init` la ritrovi.",
        "en": "Interrupted. {label}: the generation goes on in the Studio; launching "
        "`ut init` again finds it.",
    },
    "init.errors.STATE_CHANGED": {
        "it": "Il progetto continua a cambiare mentre ut init lavora ({code}): forse è aperto "
        "anche nell'interfaccia web. Finisci lì le modifiche, poi rilancia `ut init`.",
        "en": "The project keeps changing while ut init works ({code}): perhaps it is open in "
        "the web interface too. Finish the changes there, then launch `ut init` again.",
    },
    "init.errors.GATE_REFUSED": {
        "it": 'Lo Studio non accetta l\'approvazione del passo "{step}" ({code}). Apri il '
        "progetto nell'interfaccia web per vedere perché.",
        "en": 'The Studio does not accept the approval of the step "{step}" ({code}). Open the '
        "project in the web interface to see why.",
    },
    "init.errors.BRIEF_INCOMPLETE": {
        "it": "Il brief non si può approvare, mancano questi punti: {fields}. Rilancia "
        "`ut init` per correggerli.",
        "en": "The brief cannot be approved, these points are missing: {fields}. Launch "
        "`ut init` again to correct them.",
    },
    "init.errors.PROJECT_ALREADY_LINKED": {
        "it": "La cartella {root} è già collegata a un altro progetto dello Studio: --project "
        "non può collegarla a un secondo. Usa una cartella nuova.",
        "en": "The folder {root} is already linked to another project of the Studio: "
        "--project cannot link it to a second one. Use a new folder.",
    },
    "init.errors.NAME_INVALID": {
        "it": "Il nome del progetto deve avere da 1 a {limit} caratteri.",
        "en": "The name of the project must have from 1 to {limit} characters.",
    },
    "init.errors.IDEA_INVALID": {
        "it": "L'idea deve avere da 1 a {limit} caratteri.",
        "en": "The idea must have from 1 to {limit} characters.",
    },
    "init.errors.PROJECT_ID_INVALID": {
        "it": "\"{value}\" non è l'identificativo di un progetto: lo trovi nell'indirizzo "
        "della pagina del progetto nell'interfaccia web.",
        "en": '"{value}" is not the identifier of a project: you find it in the address of '
        "the page of the project in the web interface.",
    },
    "init.errors.TEAM_BLOCKED": {
        "it": "La squadra non si può proporre: il brief insieme chiede ed esclude questi "
        "ruoli: {agents}.{details} Correggi il brief nello Studio web (passo Brief, "
        "«Modifica il brief di persona»), poi rilancia `ut init`.",
        "en": "The team cannot be proposed: the brief both asks for and excludes these "
        "roles: {agents}.{details} Correct the brief in the web Studio (step Brief, "
        "«Edit the brief yourself»), then launch `ut init` again.",
    },
    "init.errors.NO_PROFILE_CONFIRMED": {
        "it": "Nessun profilo degli utenti è confermato, quindi gli User Twin non si possono "
        "creare. Apri il progetto nell'interfaccia web per rivedere i profili.",
        "en": "No user profile is confirmed, so the User Twins cannot be created. Open the "
        "project in the web interface to review the profiles.",
    },
    "init.errors.ANSWERS_FILE_INVALID": {
        "it": "Il file delle risposte {path} non è valido (`{entry}`).",
        "en": "The answers file {path} is not valid (`{entry}`).",
    },
    "init.errors.ANSWERS_FILE_INVALID.unreadable": {
        "it": "Non riesco a leggere il file delle risposte {path}: controlla che esista e che "
        "non superi 1 MB.",
        "en": "The answers file {path} cannot be read: check that it exists and that it is "
        "not larger than 1 MB.",
    },
    "init.errors.ANSWERS_FILE_INVALID.not_json": {
        "it": "Il file delle risposte {path} non è un documento JSON valido in UTF-8.",
        "en": "The answers file {path} is not a valid JSON document in UTF-8.",
    },
    "init.errors.ANSWERS_FILE_INVALID.not_object": {
        "it": "Il file delle risposte {path} deve contenere un oggetto JSON, tra parentesi graffe.",
        "en": "The answers file {path} must hold a JSON object, between curly brackets.",
    },
    "init.errors.ANSWERS_FILE_INVALID.unknown_key": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` non esiste. Le chiavi "
        "possibili qui sono: {allowed}.",
        "en": "In the answers file {path} the key `{entry}` does not exist. The possible keys "
        "here are: {allowed}.",
    },
    "init.errors.ANSWERS_FILE_INVALID.choice": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` vale {value}, ma deve essere "
        "uno di questi valori: {allowed}.",
        "en": "In the answers file {path} the key `{entry}` is {value}, but it must be one of "
        "these values: {allowed}.",
    },
    "init.errors.ANSWERS_FILE_INVALID.text": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` deve essere un testo non "
        "vuoto di al massimo {limit} caratteri.",
        "en": "In the answers file {path} the key `{entry}` must be a text that is not empty, "
        "of at most {limit} characters.",
    },
    "init.errors.ANSWERS_FILE_INVALID.texts": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` deve essere un testo oppure "
        "un elenco di testi, non vuoti e non troppo lunghi.",
        "en": "In the answers file {path} the key `{entry}` must be a text or a list of texts, "
        "not empty and not too long.",
    },
    "init.errors.ANSWERS_FILE_INVALID.object": {
        "it": "Nel file delle risposte {path} la chiave `{entry}` deve essere un oggetto JSON, "
        "tra parentesi graffe.",
        "en": "In the answers file {path} the key `{entry}` must be a JSON object, between "
        "curly brackets.",
    },
    "init.errors.ANSWERS_FILE_INVALID.missing": {
        "it": "Nel file delle risposte {path} manca la chiave `{entry}`, che serve per creare un "
        "progetto nuovo: aggiungila, oppure usa l'opzione --{entry}.",
        "en": "The answers file {path} lacks the key `{entry}`, which is needed to create a new "
        "project: add it, or use the option --{entry}.",
    },
}
