export const humanValidationCopy = {
  it: {
    title: "Ipotesi ed esiti",
    prevalidation: "Pre-validazione sintetica",
    candidates: "Candidate da verificare",
    candidateIntro:
      "Le candidate derivano dai twin e dai rilievi. Si salva un'ipotesi operativa quando la scegli e completi una domanda o un compito.",
    showCandidates: "Mostra le candidate",
    showAll: "Mostra tutte le candidate",
    hide: "Nascondi",
    details: "Dettagli",
    choose: "Scegli e completa",
    operational: "Ipotesi operativa",
    operationalPlural: "Ipotesi operative",
    empty: "Nessuna ipotesi operativa salvata.",
    noCandidates: "Nessuna candidata corrente da verificare.",
    loading: "Leggo ipotesi ed esiti…",
    failed: "Non è stato possibile completare l'operazione.",
    stale: "Il contesto è cambiato. Aggiorna i dati e scegli i riferimenti correnti.",
    sourceRetired: "La fonte è ritirata. Scegli una fonte attiva per il nuovo esito.",
    sourceUnavailable: "Fonte senza testo originale",
    citationInvalid:
      "La citazione e la riga devono individuare una sola occorrenza esatta nel testo della fonte.",
    sourceInvalid:
      "Il tipo di sessione deve corrispondere alla provenienza dichiarata dalla fonte.",
    invalid: "Completa i riferimenti, una domanda o un compito, che cosa osservare e i limiti.",
    outcomeInvalid:
      "Completa il riferimento anonimizzato, la fonte, la citazione, la riga e i limiti.",
    refresh: "Aggiorna",
    saved: "Ipotesi salvata.",
    revised: "Nuova versione dell'ipotesi salvata.",
    recorded: "Esito registrato sulla versione scelta dell'ipotesi.",
    question: "Domanda",
    task: "Compito",
    questionOrTask: "Domanda o compito",
    concrete: "Scrivi almeno una domanda o un compito concreto. La compilazione spetta a te.",
    observe: "Che cosa osservare",
    observeHelp: "Un punto per riga, fino a 24 punti di 500 caratteri ciascuno.",
    limitations: "Limiti",
    twin: "Twin",
    scenario: "Scenario",
    design: "Design di riferimento",
    origin: "Origine",
    select: "Scegli…",
    linkMissing: "Collegamento da completare",
    explicitLink:
      "La scelta dello scenario e del design è tua. I collegamenti derivati sono indicati nei dettagli della candidata.",
    alternative: "Alternativa del mockup (facoltativa)",
    anchors: "Elementi del mockup (facoltativi)",
    anchorHelp:
      "Riusa gli elementi della versione scelta. Questo collegamento non assegna un elemento a un singolo passo dello scenario.",
    save: "Salva ipotesi operativa",
    saveVersion: "Salva nuova versione",
    cancel: "Annulla",
    revise: "Rivedi ipotesi",
    chooseForRevision: "Scegli una candidata corrente per la nuova versione dell'ipotesi",
    version: "Versione",
    previous: "Versione precedente",
    history: "Versioni precedenti",
    source: "Fonte",
    outcomes: "Esiti",
    record: "Registra esito",
    noOutcomes: "Nessun esito registrato per questa versione.",
    human: "Sessione con persone",
    synthetic: "Prova sintetica, non empirica",
    sessionKind: "Tipo di sessione",
    sessionRef: "Riferimento anonimizzato della sessione",
    sessionRefHelp: "Usa un codice come SES-001 o SYN-001, senza nomi o email.",
    outcome: "Esito della sessione",
    coverage: "Copertura",
    complete: "Evidenza completa per questa ipotesi",
    partial: "Evidenza parziale",
    quote: "Citazione esatta dalla fonte",
    line: "Riga iniziale della citazione",
    showOriginal: "Mostra testo originale",
    sourceMethod: "Metodo",
    sourceContext: "Contesto",
    sourceDate: "Data della raccolta",
    saveOutcome: "Registra esito",
    retired: "Esito ritirato",
    missingSource: "La versione esatta della fonte non è disponibile.",
    returnEvidence: "Apri fonte e revisione delle evidenze",
    addEvidence: "Inserisci gli appunti come evidenza",
    noSources:
      "Nessuna fonte attiva con testo disponibile per questo tipo di sessione. Inserisci prima gli appunti nelle evidenze.",
    noPromotion:
      "Gli esiti restano collegati all'ipotesi e alla fonte. Le modifiche dei twin passano dalla revisione delle evidenze e dalla tua decisione.",
    ownerDecision: "La tua decisione",
    noHuman: "Nessun esito attivo da sessioni con persone.",
    humanSummary: "Esiti attivi da sessioni con persone",
    syntheticSummary: "Esiti attivi da prove sintetiche",
    retiredHelp:
      "La fonte ritirata resta nello storico con la citazione. Senza altri esiti umani attivi l'ipotesi torna da verificare.",
    walkthrough: "Percorso dello scenario",
    openWalkthrough: "Apri percorso",
    walkthroughIntro:
      "Compito e passi provengono dallo scenario. La navigazione del mockup è una prova software.",
    steps: "Passi",
    expected: "Esito atteso nello scenario",
    anchorCandidates: "Elementi pertinenti allo scenario",
    anchorCandidatesHelp:
      "Sono candidati per lo scenario; manca un collegamento attestato al singolo passo.",
    screen: "Mostra schermata",
    noObserve:
      "Che cosa osservare non è specificato per questo passo. Completa l'ipotesi operativa.",
    noTask: "Il compito non è disponibile nella versione dello scenario.",
    noSteps: "I passi non sono disponibili nella versione dello scenario.",
    noScenarios: "Nessuno scenario disponibile per questo mockup.",
    omitted: "Alcuni dati non sono disponibili in questa vista.",
    kinds: {
      DESIGN_CONCERN: "Criticità",
      SYNTHETIC_DESIGN_CRITIQUE: "Parere del twin",
      SYNTHETIC_FINDING: "Osservazione del twin",
    },
    states: {
      TO_VERIFY: "Da verificare",
      CONFIRMED: "Confermata",
      REFUTED: "Smentita",
      UNCERTAIN: "Incerta",
      CONTESTED: "Esiti in disaccordo",
    },
    gaps: {
      MISSING_DESIGN: "Manca il design collegato",
      VALIDATION_REFERENCE_UNAVAILABLE: "Il riferimento esatto non è disponibile",
      STEP_ANCHOR_NOT_ATTESTED: "Manca il collegamento attestato fra questo passo e un elemento",
      SCENARIO_STEPS_UNAVAILABLE: "Passi dello scenario non disponibili",
      MISSING_MOCKUP_ANCHOR: "Manca un elemento del mockup collegato allo scenario",
      SCENARIO_LEVEL_ANCHORS_ONLY:
        "Gli elementi sono collegati allo scenario, non ai singoli passi",
      SOFTWARE_NAVIGATION_NOT_HUMAN_OBSERVATION:
        "Navigare il mockup non è un'osservazione su persone",
    },
  },
  en: {
    title: "Hypotheses and outcomes",
    prevalidation: "Synthetic pre-validation",
    candidates: "Candidates to verify",
    candidateIntro:
      "Candidates are derived from twins and findings. An operational hypothesis is saved when you choose it and complete a question or task.",
    showCandidates: "Show candidates",
    showAll: "Show all candidates",
    hide: "Hide",
    details: "Details",
    choose: "Choose and complete",
    operational: "Operational hypothesis",
    operationalPlural: "Operational hypotheses",
    empty: "No operational hypothesis saved.",
    noCandidates: "No current candidate to verify.",
    loading: "Reading hypotheses and outcomes…",
    failed: "The operation could not be completed.",
    stale: "The context has changed. Refresh the data and choose the current references.",
    sourceRetired: "The source is retired. Choose an active source for the new outcome.",
    sourceUnavailable: "Source without original text",
    citationInvalid: "The quote and line must identify one exact occurrence in the source text.",
    sourceInvalid: "The session type must match the provenance declared by the source.",
    invalid: "Complete the references, a question or task, what to observe and the limitations.",
    outcomeInvalid: "Complete the anonymised reference, source, quote, line and limitations.",
    refresh: "Refresh",
    saved: "Hypothesis saved.",
    revised: "New hypothesis version saved.",
    recorded: "Outcome recorded on the chosen hypothesis version.",
    question: "Question",
    task: "Task",
    questionOrTask: "Question or task",
    concrete: "Write at least one concrete question or task. You complete these fields.",
    observe: "What to observe",
    observeHelp: "One point per line, up to 24 points of 500 characters each.",
    limitations: "Limitations",
    twin: "Twin",
    scenario: "Scenario",
    design: "Referenced design",
    origin: "Origin",
    select: "Choose…",
    linkMissing: "Link to complete",
    explicitLink:
      "You choose the scenario and design. Derived links are shown in the candidate details.",
    alternative: "Mockup alternative (optional)",
    anchors: "Mockup elements (optional)",
    anchorHelp:
      "Reuse elements of the chosen version. This link does not assign an element to an individual scenario step.",
    save: "Save operational hypothesis",
    saveVersion: "Save new version",
    cancel: "Cancel",
    revise: "Revise hypothesis",
    chooseForRevision: "Choose a current candidate for the new hypothesis version",
    version: "Version",
    previous: "Previous version",
    history: "Previous versions",
    source: "Source",
    outcomes: "Outcomes",
    record: "Record outcome",
    noOutcomes: "No outcome recorded for this version.",
    human: "Session with people",
    synthetic: "Synthetic exercise, not empirical",
    sessionKind: "Session type",
    sessionRef: "Anonymised session reference",
    sessionRefHelp: "Use a code such as SES-001 or SYN-001, without names or emails.",
    outcome: "Session outcome",
    coverage: "Coverage",
    complete: "Complete evidence for this hypothesis",
    partial: "Partial evidence",
    quote: "Exact quote from the source",
    line: "Quote starting line",
    showOriginal: "Show original text",
    sourceMethod: "Method",
    sourceContext: "Context",
    sourceDate: "Collection date",
    saveOutcome: "Record outcome",
    retired: "Retired outcome",
    missingSource: "The exact source version is unavailable.",
    returnEvidence: "Open source and evidence review",
    addEvidence: "Add session notes as evidence",
    noSources:
      "No active source with available text for this session type. Add the notes as evidence first.",
    noPromotion:
      "Outcomes stay linked to the hypothesis and source. Twin changes go through evidence review and your decision.",
    ownerDecision: "Your decision",
    noHuman: "No active outcome from sessions with people.",
    humanSummary: "Active outcomes from sessions with people",
    syntheticSummary: "Active outcomes from synthetic exercises",
    retiredHelp:
      "The retired source stays in history with its quote. Without other active human outcomes the hypothesis goes back to awaiting verification.",
    walkthrough: "Scenario walkthrough",
    openWalkthrough: "Open walkthrough",
    walkthroughIntro:
      "Task and steps come from the scenario. Navigating the mockup is a software exercise.",
    steps: "Steps",
    expected: "Expected outcome in the scenario",
    anchorCandidates: "Elements relevant to the scenario",
    anchorCandidatesHelp:
      "They are candidates for the scenario; an attested link to each step is missing.",
    screen: "Show screen",
    noObserve:
      "What to observe is not specified for this step. Complete the operational hypothesis.",
    noTask: "The task is unavailable in this scenario version.",
    noSteps: "The steps are unavailable in this scenario version.",
    noScenarios: "No scenario available for this mockup.",
    omitted: "Some data is unavailable in this view.",
    kinds: {
      DESIGN_CONCERN: "Concern",
      SYNTHETIC_DESIGN_CRITIQUE: "Twin opinion",
      SYNTHETIC_FINDING: "Twin observation",
    },
    states: {
      TO_VERIFY: "To verify",
      CONFIRMED: "Confirmed",
      REFUTED: "Refuted",
      UNCERTAIN: "Uncertain",
      CONTESTED: "Conflicting outcomes",
    },
    gaps: {
      MISSING_DESIGN: "The linked design is missing",
      VALIDATION_REFERENCE_UNAVAILABLE: "The exact reference is unavailable",
      STEP_ANCHOR_NOT_ATTESTED: "The attested link between this step and an element is missing",
      SCENARIO_STEPS_UNAVAILABLE: "Scenario steps unavailable",
      MISSING_MOCKUP_ANCHOR: "No mockup element linked to the scenario",
      SCENARIO_LEVEL_ANCHORS_ONLY: "Elements are linked to the scenario, not to individual steps",
      SOFTWARE_NAVIGATION_NOT_HUMAN_OBSERVATION:
        "Navigating the mockup is not an observation of people",
    },
  },
} as const;
