export const researchEvidenceCopy = {
  en: {
    title: "Evidence for the twins",
    intro:
      "Add anonymised interview notes, observations or text documents. The model suggests what they support, contradict or add; you decide what enters the twin.",
    add: "Add evidence",
    warning:
      "The text you add will be sent to the model when you request a proposal. Remove names and personal details first. Adding text or approving a proposal does not make it empirical research or validation with real users.",
    acknowledge: "I have anonymised the text and understand that it will be sent to the model.",
    cancel: "Cancel",
    save: "Save evidence",
    revise: "Add a new version",
    titleLabel: "Title",
    sourceKind: "Where the text comes from",
    sourceRef: "Source reference",
    context: "Context",
    method: "How it was collected",
    date: "Date or period (optional)",
    limitations: "Limits of the source",
    empirical:
      "I declare that this source comes from empirical research, as described in the method and limits.",
    text: "Anonymised text",
    file: "Or choose a UTF-8 text file (.txt or .md)",
    limit: "Use at most 24,000 characters and 32 KiB per source. Divide a longer text into parts.",
    invalidFile: "Choose a valid UTF-8 .txt or .md file without binary content.",
    missingFields: "Complete the title, source reference, context, method and limits.",
    limitError:
      "The evidence limit was reached. Divide the text into parts; the project can hold 1 MiB of text and 50 versions.",
    failed: "The operation could not be completed. Try again.",
    stale: "The evidence or twin changed. Reload the sources and review the new context.",
    unavailable: "The original text is no longer available.",
    empty: "No evidence added yet.",
    details: "Source details",
    version: "Version",
    latest: "Latest version",
    earlier: "Earlier version",
    active: "Available",
    retired: "Retired",
    nonEmpirical: "Non-empirical source",
    empiricalSource: "Declared empirical source",
    original: "Read the original text",
    hideOriginal: "Hide the original text",
    hash: "Content hash",
    chars: "characters",
    quote: "Exact quote",
    lines: "Lines",
    propose: "Suggest changes for this twin",
    selectTwin: "Twin to review",
    prerequisite:
      "Approve the brief and the twins before requesting a proposal. A design is not required.",
    generating: "The model is reading the evidence. This may take a few minutes…",
    reviewing: "Review the proposed changes",
    rejected: "Changes refused because their quotes or structure could not be verified: {count}.",
    noChanges:
      "No change passed the checks. The source and the number of refused changes remain recorded.",
    keep: "Keep",
    correct: "Correct the interpretation (the current profile value stays)",
    correctAddition: "Correct the new information to add",
    approve: "Approve the selected changes",
    discard: "Discard the proposal",
    approved:
      "Changes approved. Review the linked Definition, design evaluation and Dossier; earlier identities and versions remain.",
    discarded: "Proposal discarded. The twin stays as it was.",
    decisionWarning: "Your approval updates the twin. It does not validate it with real people.",
    basis: "Why this change is proposed",
    retire: "Retire evidence",
    retireWarning:
      "Claims supported only by this evidence become hypotheses again, and dependent sections reopen. Other independent evidence remains. No content is regenerated.",
    reason: "Why you are retiring it",
    retiredDone: "Evidence retired. Review the reopened sections.",
    retiredReview:
      "Evidence retired. Review the current twin profile: its pending draft has not been approved. Dependent sections need another look.",
    deleteText: "Delete the original text",
    deleteWarning:
      "The stored original text will be deleted. Metadata, hashes and historical quotes remain, as may existing exports, backups and copies sent to the model.",
    deleteAcknowledge: "I understand what will be deleted and what may remain.",
    deletedDone: "Original text deleted; source references and historical quotes remain.",
    saved: "Evidence saved. Choose a twin to request a proposal.",
    revised:
      "New version saved. Existing claims still cite their original version; retire it if it no longer applies.",
    refresh: "Reload sources",
    effects: { SUPPORTS: "Supports", CONTRADICTS: "Contradicts", ADDS: "Adds information" },
    kinds: {
      OWNER_INPUT: "Your notes or a test text",
      EMPIRICAL_RESEARCH: "Empirical research",
      HUMAN_REVIEW: "Review by a person",
      PROJECT_BRIEF: "Project brief",
      SYSTEM_ARTIFACT: "Project document",
      MODEL_OUTPUT: "Model output (simulated)",
    },
  },
  it: {
    title: "Evidenze per i twin",
    intro:
      "Aggiungi appunti di interviste, osservazioni o documenti di testo anonimizzati. Il modello propone che cosa sostengono, contraddicono o aggiungono; tu decidi che cosa entra nel twin.",
    add: "Aggiungi evidenza",
    warning:
      "Il testo che aggiungi sarà inviato al modello quando chiedi una proposta. Prima rimuovi nomi e dati personali. Inserire un testo o approvare una proposta non lo rende ricerca empirica né validazione con utenti reali.",
    acknowledge: "Ho anonimizzato il testo e so che sarà inviato al modello.",
    cancel: "Annulla",
    save: "Salva evidenza",
    revise: "Aggiungi una nuova versione",
    titleLabel: "Titolo",
    sourceKind: "Da dove viene il testo",
    sourceRef: "Riferimento della fonte",
    context: "Contesto",
    method: "Come è stato raccolto",
    date: "Data o periodo (facoltativo)",
    limitations: "Limiti della fonte",
    empirical:
      "Dichiaro che questa fonte proviene da ricerca empirica, descritta nel metodo e nei limiti.",
    text: "Testo anonimizzato",
    file: "Oppure scegli un file di testo UTF-8 (.txt o .md)",
    limit: "Al massimo 24.000 caratteri e 32 KiB per evidenza. Dividi un testo più lungo in parti.",
    invalidFile: "Scegli un file .txt o .md UTF-8 valido, senza contenuto binario.",
    missingFields: "Completa titolo, riferimento della fonte, contesto, metodo e limiti.",
    limitError:
      "È stato raggiunto il limite delle evidenze. Dividi il testo in parti; il progetto può contenere 1 MiB di testo e 50 versioni.",
    failed: "Non è stato possibile completare l'operazione. Riprova.",
    stale: "La fonte o il twin sono cambiati. Ricarica le fonti e controlla il nuovo contesto.",
    unavailable: "Il testo originale non è più disponibile.",
    empty: "Non hai ancora aggiunto evidenze.",
    details: "Dettagli della fonte",
    version: "Versione",
    latest: "Versione più recente",
    earlier: "Versione precedente",
    active: "Disponibile",
    retired: "Ritirata",
    nonEmpirical: "Fonte non empirica",
    empiricalSource: "Fonte dichiarata empirica",
    original: "Leggi il testo originale",
    hideOriginal: "Nascondi il testo originale",
    hash: "Hash del contenuto",
    chars: "caratteri",
    quote: "Citazione esatta",
    lines: "Righe",
    propose: "Proponi cambiamenti per questo twin",
    selectTwin: "Twin da rivedere",
    prerequisite: "Approva il brief e i twin prima di chiedere una proposta. Il design non serve.",
    generating: "Il modello sta leggendo l'evidenza. Può richiedere alcuni minuti…",
    reviewing: "Controlla i cambiamenti proposti",
    rejected: "Cambiamenti rifiutati perché citazioni o struttura non erano verificabili: {count}.",
    noChanges:
      "Nessun cambiamento ha superato i controlli. La fonte e il numero dei rifiuti restano registrati.",
    keep: "Tieni",
    correct: "Correggi l'interpretazione (il valore attuale del profilo resta)",
    correctAddition: "Correggi la nuova informazione da aggiungere",
    approve: "Approva i cambiamenti selezionati",
    discard: "Scarta la proposta",
    approved:
      "Cambiamenti approvati. Rivedi la Definizione collegata, la valutazione del design e il Dossier; identità e versioni precedenti restano.",
    discarded: "Proposta scartata. Il twin resta com'era.",
    decisionWarning: "La tua approvazione aggiorna il twin. Non lo valida con persone reali.",
    basis: "Perché viene proposto questo cambiamento",
    retire: "Ritira evidenza",
    retireWarning:
      "Le affermazioni sostenute solo da questa evidenza tornano ipotesi e le sezioni dipendenti si riaprono. Le altre evidenze indipendenti restano. Nessun contenuto viene rigenerato.",
    reason: "Perché la ritiri",
    retiredDone: "Evidenza ritirata. Controlla le sezioni riaperte.",
    retiredReview:
      "Evidenza ritirata. Rivedi il profilo attuale del twin: la bozza in attesa non è stata approvata. Le sezioni dipendenti vanno ricontrollate.",
    deleteText: "Elimina il testo originale",
    deleteWarning:
      "Il testo originale conservato sarà eliminato. Restano metadati, hash e citazioni storiche; possono restare anche esportazioni, backup e copie inviate al modello.",
    deleteAcknowledge: "So che cosa viene eliminato e che cosa può restare.",
    deletedDone: "Testo originale eliminato; riferimenti e citazioni storiche restano.",
    saved: "Evidenza salvata. Scegli un twin per chiedere una proposta.",
    revised:
      "Nuova versione salvata. Le affermazioni già approvate citano ancora la loro versione originale; ritirala se non vale più.",
    refresh: "Ricarica le fonti",
    effects: { SUPPORTS: "Sostiene", CONTRADICTS: "Contraddice", ADDS: "Aggiunge informazioni" },
    kinds: {
      OWNER_INPUT: "I tuoi appunti o un testo di prova",
      EMPIRICAL_RESEARCH: "Ricerca empirica",
      HUMAN_REVIEW: "Revisione di una persona",
      PROJECT_BRIEF: "Brief del progetto",
      SYSTEM_ARTIFACT: "Documento del progetto",
      MODEL_OUTPUT: "Risposta del modello (simulata)",
    },
  },
} as const;
